// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: ADVdash

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void bannerAnim_Animation(lv_obj_t * TargetObject, int delay);
void proAnim_Animation(lv_obj_t * TargetObject, int delay);
void titleAnim_Animation(lv_obj_t * TargetObject, int delay);
void carAnim_Animation(lv_obj_t * TargetObject, int delay);
void finalTextAnim_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_WelcomeScreen
void ui_WelcomeScreen_screen_init(void);
lv_obj_t * ui_WelcomeScreen;
lv_obj_t * ui_carIMG;
lv_obj_t * ui_welcomeLabel;
lv_obj_t * ui_bannerTextA;
lv_obj_t * ui_proBannerIMG;
lv_obj_t * ui_proIMG;


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen(lv_event_t * e);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_RpmsBG;
lv_obj_t * ui_RedLineBar;
lv_obj_t * ui_RpmsBar;
lv_obj_t * ui_RpmsValue;
lv_obj_t * ui_RpmsText;
lv_obj_t * ui_GearPanel;
lv_obj_t * ui_GearValue;
lv_obj_t * ui_SpeedPanel;
lv_obj_t * ui_SpeedValue;
lv_obj_t * ui_TpsBar;
lv_obj_t * ui_Arc5;
lv_obj_t * ui_ArcValue5;
lv_obj_t * ui_ArcUnit5;
lv_obj_t * ui_ArcName5;
lv_obj_t * ui_ArcBG5;
lv_obj_t * ui_MainAletPanel;
lv_obj_t * ui_MainAlertText;
lv_obj_t * ui_MainLabelGear;
lv_obj_t * ui_MainAlertSpeed;
lv_obj_t * ui_Bar1;
lv_obj_t * ui_BarBG1;
lv_obj_t * ui_BarValue1;
lv_obj_t * ui_BarUnit1;
lv_obj_t * ui_BarName1;
lv_obj_t * ui_Bar2;
lv_obj_t * ui_BarBG2;
lv_obj_t * ui_BarName2;
lv_obj_t * ui_BarValue2;
lv_obj_t * ui_BarUnit2;
lv_obj_t * ui_Arc2;
lv_obj_t * ui_ArcValue2;
lv_obj_t * ui_ArcUnit2;
lv_obj_t * ui_ArcName2;
lv_obj_t * ui_ArcBG2;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_ArcValue1;
lv_obj_t * ui_ArcUnit1;
lv_obj_t * ui_ArcName1;
lv_obj_t * ui_ArcBG1;
lv_obj_t * ui_Arc3;
lv_obj_t * ui_ArcValue3;
lv_obj_t * ui_ArcUnit3;
lv_obj_t * ui_ArcName3;
lv_obj_t * ui_ArcBG3;
lv_obj_t * ui_Arc4;
lv_obj_t * ui_ArcValue4;
lv_obj_t * ui_ArcUnit4;
lv_obj_t * ui_ArcName4;
lv_obj_t * ui_ArcBG4;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_PanelValue1;
lv_obj_t * ui_PanelName1;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_PanelValue2;
lv_obj_t * ui_PanelName2;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_PanelValue3;
lv_obj_t * ui_PanelName3;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_PanelValue4;
lv_obj_t * ui_PanelName4;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_PanelValue5;
lv_obj_t * ui_PanelName5;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_PanelValue6;
lv_obj_t * ui_PanelName6;
lv_obj_t * ui_Bar3;
lv_obj_t * ui_BarBG3;
lv_obj_t * ui_BarName3;
lv_obj_t * ui_BarValue3;
lv_obj_t * ui_BarUnit3;
lv_obj_t * ui_Bar4;
lv_obj_t * ui_BarBG4;
lv_obj_t * ui_BarName4;
lv_obj_t * ui_BarValue4;
lv_obj_t * ui_BarUnit4;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_ButtonLabel1;
lv_obj_t * ui_CriticalAlertPanel;
lv_obj_t * ui_CriticalAlertText;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_ButtonLabel2;
lv_obj_t * ui_ClockLabel;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_ButtonLabel3;


// SCREEN: ui_GraphScreen
void ui_GraphScreen_screen_init(void);
void ui_event_GraphScreen(lv_event_t * e);
lv_obj_t * ui_GraphScreen;
lv_obj_t * ui_Chart2;


// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
lv_obj_t * ui_SettingsScreen;
lv_obj_t * ui_Roller;
lv_obj_t * ui_SetingsPanel;
lv_obj_t * ui_SelectPanel;
lv_obj_t * ui_GaugeNumberD;
lv_obj_t * ui_GaugeTypeD;
lv_obj_t * ui_HighAlertPanel;
lv_obj_t * ui_HWAPanel;
lv_obj_t * ui_HWATittle;
lv_obj_t * ui_HWALabel;
void ui_event_HWASlider(lv_event_t * e);
lv_obj_t * ui_HWASlider;
lv_obj_t * ui_HDAPanel;
lv_obj_t * ui_HDATittle;
lv_obj_t * ui_HDALabel;
void ui_event_HDASlider(lv_event_t * e);
lv_obj_t * ui_HDASlider;
lv_obj_t * ui_LowAlertPanel;
lv_obj_t * ui_LWAPanel;
lv_obj_t * ui_LWATittle;
lv_obj_t * ui_LWALabel;
void ui_event_LWASlider(lv_event_t * e);
lv_obj_t * ui_LWASlider;
lv_obj_t * ui_LDAPanel;
lv_obj_t * ui_LDATittle;
lv_obj_t * ui_LDALabel;
void ui_event_LDASlider(lv_event_t * e);
lv_obj_t * ui_LDASlider;
lv_obj_t * ui_SelectUnit;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_TempUnitText;
lv_obj_t * ui_TempUnitD;
lv_obj_t * ui_Panel9;
lv_obj_t * ui_PressUnitText;
lv_obj_t * ui_PressUnitD;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_SpeedUnitText;
lv_obj_t * ui_SpeedUnitD;
lv_obj_t * ui_Panel7;
void ui_event_SaveBTN(lv_event_t * e);
lv_obj_t * ui_SaveBTN;
lv_obj_t * ui_Label3;
void ui_event_DefaultBTN(lv_event_t * e);
lv_obj_t * ui_DefaultBTN;
lv_obj_t * ui_Label2;
void ui_event_ResetBTN(lv_event_t * e);
lv_obj_t * ui_ResetBTN;
lv_obj_t * ui_Label1;
void ui_event_ExitBtn(lv_event_t * e);
lv_obj_t * ui_ExitBtn;
lv_obj_t * ui_Label4;


// SCREEN: ui_FinalScreen
void ui_FinalScreen_screen_init(void);
void ui_event_FinalScreen(lv_event_t * e);
lv_obj_t * ui_FinalScreen;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_bannerTextA2;
lv_obj_t * ui_proBannerIMG2;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_advecu[1] = {&ui_img_advecu200_png};
const lv_img_dsc_t * ui_imgset_e[1] = {&ui_img_e30_png};
const lv_img_dsc_t * ui_imgset_rpmscalev[1] = {&ui_img_rpmscalev2_png};
const lv_img_dsc_t * ui_imgset_usersett[1] = {&ui_img_usersett50_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void bannerAnim_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, 260, 222);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void proAnim_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -260, -214);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void titleAnim_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}
void carAnim_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}
void finalTextAnim_Animation(lv_obj_t * TargetObject, int delay)
{

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_MainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_FinalScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_FinalScreen_screen_init);
        _ui_screen_delete(&ui_MainScreen);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_SettingsScreen_screen_init);
        _ui_screen_delete(&ui_MainScreen);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_CriticalAlertPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_CriticalAlertPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_flag_modify(ui_MainAletPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_GraphScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
        _ui_screen_delete(&ui_GraphScreen);
    }
}
void ui_event_HWASlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_HWALabel, target, "", "");
    }
}
void ui_event_HDASlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_HDALabel, target, "", "");
    }
}
void ui_event_LWASlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LWALabel, target, "", "");
    }
}
void ui_event_LDASlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_LDALabel, target, "", "");
    }
}
void ui_event_SaveBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        saveSettings(e);
    }
}
void ui_event_DefaultBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        DefaultSettingsAction(e);
    }
}
void ui_event_ResetBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        ResetAction(e);
    }
}
void ui_event_ExitBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
        _ui_screen_delete(&ui_SettingsScreen);
    }
}
void ui_event_FinalScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainScreen_screen_init);
        _ui_screen_delete(&ui_FinalScreen);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_WelcomeScreen_screen_init();
    ui_MainScreen_screen_init();
    ui_GraphScreen_screen_init();
    ui_SettingsScreen_screen_init();
    ui_FinalScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_WelcomeScreen);
}
