// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: ADVdash

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_RpmsBG;
lv_obj_t *ui_RedLineBar;
lv_obj_t *ui_RpmsBar;
lv_obj_t *ui_RpmsValue;
lv_obj_t *ui_RpmsText;
lv_obj_t *ui_GearPanel;
lv_obj_t *ui_GearValue;
lv_obj_t *ui_SpeedPanel;
lv_obj_t *ui_SpeedValue;
lv_obj_t *ui_TpsBar;
lv_obj_t *ui_MainArc;
lv_obj_t *ui_MainArcValue;
lv_obj_t *ui_MainArcUnit;
lv_obj_t *ui_MainArcName;
lv_obj_t *ui_mainArcBG;
lv_obj_t *ui_MainAletPanel;
lv_obj_t *ui_MainAlertText;
lv_obj_t *ui_MainLabelGear;
lv_obj_t *ui_MainAlertSpeed;
lv_obj_t *ui_Bar1;
lv_obj_t *ui_Bar1BG;
lv_obj_t *ui_Bar1Value;
lv_obj_t *ui_Bar1Unit;
lv_obj_t *ui_Bar1Name;
lv_obj_t *ui_Bar2;
lv_obj_t *ui_Bar2BG;
lv_obj_t *ui_Bar2Name;
lv_obj_t *ui_Bar2Value;
lv_obj_t *ui_Bar2Unit;
lv_obj_t *ui_Arc2;
lv_obj_t *ui_ArcValue2;
lv_obj_t *ui_ArcUnit2;
lv_obj_t *ui_ArcName2;
lv_obj_t *ui_ArcBG2;
lv_obj_t *ui_Arc1;
lv_obj_t *ui_ArcValue1;
lv_obj_t *ui_ArcUnit1;
lv_obj_t *ui_ArcName1;
lv_obj_t *ui_ArcBG1;
lv_obj_t *ui_Arc3;
lv_obj_t *ui_ArcValue3;
lv_obj_t *ui_ArcUnit3;
lv_obj_t *ui_ArcName3;
lv_obj_t *ui_ArcBG3;
lv_obj_t *ui_Arc4;
lv_obj_t *ui_ArcValue4;
lv_obj_t *ui_ArcUnit4;
lv_obj_t *ui_ArcName4;
lv_obj_t *ui_ArcBG4;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
