// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: ADVdash

#ifndef _ADVDASH_UI_H
#define _ADVDASH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void bannerAnim_Animation(lv_obj_t * TargetObject, int delay);
void proAnim_Animation(lv_obj_t * TargetObject, int delay);
void titleAnim_Animation(lv_obj_t * TargetObject, int delay);
void carAnim_Animation(lv_obj_t * TargetObject, int delay);
void finalTextAnim_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_WelcomeScreen
void ui_WelcomeScreen_screen_init(void);
extern lv_obj_t * ui_WelcomeScreen;
extern lv_obj_t * ui_carIMG;
extern lv_obj_t * ui_welcomeLabel;
extern lv_obj_t * ui_bannerTextA;
extern lv_obj_t * ui_proBannerIMG;
extern lv_obj_t * ui_proIMG;
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_RpmsBG;
extern lv_obj_t * ui_RedLineBar;
extern lv_obj_t * ui_RpmsBar;
extern lv_obj_t * ui_RpmsValue;
extern lv_obj_t * ui_RpmsText;
extern lv_obj_t * ui_GearPanel;
extern lv_obj_t * ui_GearValue;
extern lv_obj_t * ui_SpeedPanel;
extern lv_obj_t * ui_SpeedValue;
extern lv_obj_t * ui_TpsBar;
extern lv_obj_t * ui_Arc5;
extern lv_obj_t * ui_ArcValue5;
extern lv_obj_t * ui_ArcUnit5;
extern lv_obj_t * ui_ArcName5;
extern lv_obj_t * ui_ArcBG5;
extern lv_obj_t * ui_MainAletPanel;
extern lv_obj_t * ui_MainAlertText;
extern lv_obj_t * ui_MainLabelGear;
extern lv_obj_t * ui_MainAlertSpeed;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_BarBG1;
extern lv_obj_t * ui_BarValue1;
extern lv_obj_t * ui_BarUnit1;
extern lv_obj_t * ui_BarName1;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_BarBG2;
extern lv_obj_t * ui_BarName2;
extern lv_obj_t * ui_BarValue2;
extern lv_obj_t * ui_BarUnit2;
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_ArcValue2;
extern lv_obj_t * ui_ArcUnit2;
extern lv_obj_t * ui_ArcName2;
extern lv_obj_t * ui_ArcBG2;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_ArcValue1;
extern lv_obj_t * ui_ArcUnit1;
extern lv_obj_t * ui_ArcName1;
extern lv_obj_t * ui_ArcBG1;
extern lv_obj_t * ui_Arc3;
extern lv_obj_t * ui_ArcValue3;
extern lv_obj_t * ui_ArcUnit3;
extern lv_obj_t * ui_ArcName3;
void ui_event_ArcBG3(lv_event_t * e);
extern lv_obj_t * ui_ArcBG3;
extern lv_obj_t * ui_Arc4;
extern lv_obj_t * ui_ArcValue4;
extern lv_obj_t * ui_ArcUnit4;
extern lv_obj_t * ui_ArcName4;
void ui_event_ArcBG4(lv_event_t * e);
extern lv_obj_t * ui_ArcBG4;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_PanelValue1;
extern lv_obj_t * ui_PanelName1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_PanelValue2;
extern lv_obj_t * ui_PanelName2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_PanelValue3;
extern lv_obj_t * ui_PanelName3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_PanelValue4;
extern lv_obj_t * ui_PanelName4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_PanelValue5;
extern lv_obj_t * ui_PanelName5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_PanelValue6;
extern lv_obj_t * ui_PanelName6;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_BarBG3;
extern lv_obj_t * ui_BarName3;
extern lv_obj_t * ui_BarValue3;
extern lv_obj_t * ui_BarUnit3;
extern lv_obj_t * ui_Bar4;
extern lv_obj_t * ui_BarBG4;
extern lv_obj_t * ui_BarName4;
extern lv_obj_t * ui_BarValue4;
extern lv_obj_t * ui_BarUnit4;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_ButtonLabel1;
extern lv_obj_t * ui_CriticalAlertPanel;
extern lv_obj_t * ui_CriticalAlertText;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_ButtonLabel2;
extern lv_obj_t * ui_ClockLabel;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_ButtonLabel3;
extern lv_obj_t * ui_ConfigPanel;
extern lv_obj_t * ui_ConfigName;
void ui_event_ConfigExit(lv_event_t * e);
extern lv_obj_t * ui_ConfigExit;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_GaugeType;
extern lv_obj_t * ui_ConfigText;
void ui_event_HWASlider(lv_event_t * e);
extern lv_obj_t * ui_HWASlider;
void ui_event_HDASlider(lv_event_t * e);
extern lv_obj_t * ui_HDASlider;
void ui_event_LWASlider(lv_event_t * e);
extern lv_obj_t * ui_LWASlider;
void ui_event_LDASlider(lv_event_t * e);
extern lv_obj_t * ui_LDASlider;
extern lv_obj_t * ui_HWALabel;
extern lv_obj_t * ui_HDALabel;
extern lv_obj_t * ui_LWALabel;
extern lv_obj_t * ui_LDALabel;
extern lv_obj_t * ui_SaveBTN;
extern lv_obj_t * ui_Label9;
// SCREEN: ui_GraphScreen
void ui_GraphScreen_screen_init(void);
void ui_event_GraphScreen(lv_event_t * e);
extern lv_obj_t * ui_GraphScreen;
extern lv_obj_t * ui_Chart2;
// SCREEN: ui_FinalScreen
void ui_FinalScreen_screen_init(void);
void ui_event_FinalScreen(lv_event_t * e);
extern lv_obj_t * ui_FinalScreen;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_bannerTextA2;
extern lv_obj_t * ui_proBannerIMG2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_e30_png);    // assets/e30.png
LV_IMG_DECLARE(ui_img_banner_png);    // assets/banner.png
LV_IMG_DECLARE(ui_img_proup_png);    // assets/PROup.png
LV_IMG_DECLARE(ui_img_proadvv1amarillo_png);    // assets/ProAdvV1Amarillo.png
LV_IMG_DECLARE(ui_img_rpmscalev3t_png);    // assets/RPMscalev3T.png
LV_IMG_DECLARE(ui_img_arcscalenored_png);    // assets/arcScaleNoRed.png
LV_IMG_DECLARE(ui_img_barscale_png);    // assets/barScale.png
LV_IMG_DECLARE(ui_img_arcscalerr_png);    // assets/arcScaleRR.png
LV_IMG_DECLARE(ui_img_arcscalerb_png);    // assets/arcScaleRB.png
LV_IMG_DECLARE(ui_img_arcscale_png);    // assets/arcScale.png
LV_IMG_DECLARE(ui_img_barscalerb_png);    // assets/barScaleRB.png
LV_IMG_DECLARE(ui_img_barscalered_png);    // assets/barScaleRed.png
LV_IMG_DECLARE(ui_img_advecu200_png);    // assets/Advecu200.png
LV_IMG_DECLARE(ui_img_rpmscalev2_png);    // assets/RPMscalev2.png
LV_IMG_DECLARE(ui_img_usersett50_png);    // assets/userSett50.png



LV_FONT_DECLARE(ui_font_ArameBold100);
LV_FONT_DECLARE(ui_font_ArameBold14);
LV_FONT_DECLARE(ui_font_ArameBold150);
LV_FONT_DECLARE(ui_font_ArameBold20);
LV_FONT_DECLARE(ui_font_ArameBold30);
LV_FONT_DECLARE(ui_font_ArameBold30c);
LV_FONT_DECLARE(ui_font_ArameBold40);
LV_FONT_DECLARE(ui_font_ArameBold50);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
