// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: ADVdash

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Arc5Config(lv_event_t * e);
void Arc2Config(lv_event_t * e);
void Arc1Config(lv_event_t * e);
void Arc3Config(lv_event_t * e);
void Arc4Config(lv_event_t * e);
void GaugeTChange(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
