// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: ADVdash

#include "ui.h"
#include "controllers/uiControl/ui_enums.h"
#include "controllers/uiControl/ui_control.h"
#include "controllers/uiControl/config_manager.h"
#include "controllers/uiControl/menu_manager.h"

void ResetAction(lv_event_t *e)
{
	ESP.restart();
}

void DefaultSettingsAction(lv_event_t *e)
{
	db.resetToDefault();
	Serial.println("Reset to default");
	ESP.restart();
}

void Arc3Config(lv_event_t *e)
{
	_ui_flag_modify(ui_ConfigPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
	textConfigArc(arc_number_t::ARC_3, true);
	xTaskNotify(ui_task_handle, 3, eSetValueWithOverwrite);
}

void Arc4Config(lv_event_t *e)
{
	_ui_flag_modify(ui_ConfigPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
	textConfigArc(arc_number_t::ARC_4, true);
	xTaskNotify(ui_task_handle, 4, eSetValueWithOverwrite);
}

void Arc5Config(lv_event_t *e)
{
	_ui_flag_modify(ui_ConfigPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
	textConfigArc(arc_number_t::ARC_5, true);
	xTaskNotify(ui_task_handle, 5, eSetValueWithOverwrite);
}

void Arc2Config(lv_event_t *e)
{
	_ui_flag_modify(ui_ConfigPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
	textConfigArc(arc_number_t::ARC_2, true);
	xTaskNotify(ui_task_handle, 2, eSetValueWithOverwrite);
}

void Arc1Config(lv_event_t *e)
{
	_ui_flag_modify(ui_ConfigPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
	textConfigArc(arc_number_t::ARC_1, true);
	xTaskNotify(ui_task_handle, 1, eSetValueWithOverwrite);
}

void GaugeTChange(lv_event_t *e)
{
	dropDownChange();
}

void onChangeMenu1(lv_event_t * e)
{

	int numOptions = lv_roller_get_option_cnt(ui_Menu1);
	int selected = lv_roller_get_selected(ui_Menu1);
	lv_group_t * g = lv_group_get_default();

	if (lv_roller_get_selected(ui_Menu1) == numOptions - 1)
	{
		lv_obj_add_flag(ui_Menu1, LV_OBJ_FLAG_HIDDEN);
		lv_obj_add_flag(ui_Menu2, LV_OBJ_FLAG_HIDDEN);

	}
	else
	{
		menu_manager.rideMenuSetSelectedOptions((rideMenuOptions)selected);
		lv_group_focus_next(g);
	}
	
}

void onChangeMenu2(lv_event_t * e)
{
	int selected = lv_roller_get_selected(ui_Menu2);
	rideMenuOptions option = menu_manager.getSelectedMenuOption();

	menu_manager.manageMenuActions(option, selected);

}
