// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: ADVdash

#include "ui.h"
#include "controllers/uiControl/ui_enums.h"
#include "controllers/uiControl/ui_control.h"
#include "controllers/uiControl/ui_control.h"
#include "controllers/uiControl/config_manager.h"

void ResetAction(lv_event_t *e)
{
	ESP.restart();
}

void DefaultSettingsAction(lv_event_t *e)
{
	db.resetToDefault();
	Serial.println("Reset to default");
	ESP.restart();
}

void Arc3Config(lv_event_t *e)
{
	xTaskNotify(ui_task_handle, 3, eSetValueWithOverwrite);
}

void Arc4Config(lv_event_t *e)
{
	xTaskNotify(ui_task_handle, 4, eSetValueWithOverwrite);
}
