// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: ADVdash

#include "../ui.h"

void ui_FinalScreen_screen_init(void)
{
    ui_FinalScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FinalScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FinalScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FinalScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_FinalScreen);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -95);
    lv_obj_set_y(ui_Label5, 0);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "MAX RPMS :\nMAX CTL :\nMAX IAT :\nMAX VSS :\nMIN OIL PRESS :\nTIME :");
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_ArameBold30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_FinalScreen);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 94);
    lv_obj_set_y(ui_Label6, 0);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "8500\n105 °C\n45 °C\n130 km/h\n20 PSI\n102 min");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_ArameBold30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bannerTextA2 = lv_textarea_create(ui_FinalScreen);
    lv_obj_set_width(ui_bannerTextA2, 804);
    lv_obj_set_height(ui_bannerTextA2, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_bannerTextA2, -1);
    lv_obj_set_y(ui_bannerTextA2, 222);
    lv_obj_set_align(ui_bannerTextA2, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_bannerTextA2, "27°C | 85kpa | 09:12 pm | 07/01/2024 | 1850 msnm");
    lv_textarea_set_one_line(ui_bannerTextA2, true);
    lv_obj_set_style_text_color(ui_bannerTextA2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bannerTextA2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_bannerTextA2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bannerTextA2, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_bannerTextA2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bannerTextA2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bannerTextA2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_bannerTextA2, &ui_img_banner_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_bannerTextA2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_proBannerIMG2 = lv_img_create(ui_FinalScreen);
    lv_img_set_src(ui_proBannerIMG2, &ui_img_proup_png);
    lv_obj_set_width(ui_proBannerIMG2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_proBannerIMG2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_proBannerIMG2, -5);
    lv_obj_set_y(ui_proBannerIMG2, -218);
    lv_obj_set_align(ui_proBannerIMG2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_proBannerIMG2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_proBannerIMG2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_FinalScreen, ui_event_FinalScreen, LV_EVENT_ALL, NULL);

}
