// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: ADVdash

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RpmsBG = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_RpmsBG, &ui_img_rpmscalev3t_png);
    lv_obj_set_width(ui_RpmsBG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RpmsBG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RpmsBG, -87);
    lv_obj_set_y(ui_RpmsBG, -196);
    lv_obj_set_align(ui_RpmsBG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RpmsBG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RpmsBG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RedLineBar = lv_bar_create(ui_MainScreen);
    lv_bar_set_mode(ui_RedLineBar, LV_BAR_MODE_RANGE);
    lv_bar_set_value(ui_RedLineBar, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_RedLineBar, 20, LV_ANIM_OFF);
    lv_obj_set_width(ui_RedLineBar, 310);
    lv_obj_set_height(ui_RedLineBar, 30);
    lv_obj_set_x(ui_RedLineBar, 62);
    lv_obj_set_y(ui_RedLineBar, -181);
    lv_obj_set_align(ui_RedLineBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_RedLineBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RedLineBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RedLineBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RedLineBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RedLineBar, lv_color_hex(0xFF0303), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RedLineBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_RedLineBar, LV_BLEND_MODE_MULTIPLY, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_RpmsBar = lv_bar_create(ui_MainScreen);
    lv_bar_set_range(ui_RpmsBar, 0, 1000);
    lv_obj_set_width(ui_RpmsBar, 597);
    lv_obj_set_height(ui_RpmsBar, 40);
    lv_obj_set_x(ui_RpmsBar, -88);
    lv_obj_set_y(ui_RpmsBar, -207);
    lv_obj_set_align(ui_RpmsBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_RpmsBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RpmsBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RpmsBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RpmsBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RpmsBar, lv_color_hex(0xDCDCDC), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RpmsBar, 250, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RpmsBar, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RpmsBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RpmsBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_RpmsBar, LV_BORDER_SIDE_NONE, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_RpmsValue = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_RpmsValue, 144);
    lv_obj_set_height(ui_RpmsValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RpmsValue, -27);
    lv_obj_set_y(ui_RpmsValue, -198);
    lv_obj_set_align(ui_RpmsValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_RpmsValue, "0");
    lv_obj_set_style_text_align(ui_RpmsValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RpmsValue, &ui_font_ArameBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RpmsText = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_RpmsText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RpmsText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RpmsText, 352);
    lv_obj_set_y(ui_RpmsText, -173);
    lv_obj_set_align(ui_RpmsText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RpmsText, "RPMS");
    lv_obj_set_style_text_font(ui_RpmsText, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GearPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_GearPanel, 140);
    lv_obj_set_height(ui_GearPanel, 174);
    lv_obj_set_x(ui_GearPanel, 0);
    lv_obj_set_y(ui_GearPanel, -14);
    lv_obj_set_align(ui_GearPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GearPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_GearPanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_GearPanel, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GearPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GearPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GearPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GearValue = lv_label_create(ui_GearPanel);
    lv_obj_set_width(ui_GearValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GearValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GearValue, 0);
    lv_obj_set_y(ui_GearValue, 5);
    lv_obj_set_align(ui_GearValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GearValue, "N");
    lv_obj_set_style_text_font(ui_GearValue, &ui_font_ArameBold150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_SpeedPanel, 140);
    lv_obj_set_height(ui_SpeedPanel, 50);
    lv_obj_set_x(ui_SpeedPanel, 0);
    lv_obj_set_y(ui_SpeedPanel, -128);
    lv_obj_set_align(ui_SpeedPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpeedPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_SpeedPanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_SpeedPanel, lv_color_hex(0xC4C4C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SpeedPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SpeedPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedValue = lv_label_create(ui_SpeedPanel);
    lv_obj_set_width(ui_SpeedValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SpeedValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedValue, "---");
    lv_obj_set_style_text_color(ui_SpeedValue, lv_color_hex(0x020202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedValue, &ui_font_ArameBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TpsBar = lv_bar_create(ui_MainScreen);
    lv_bar_set_range(ui_TpsBar, 0, 10000);
    lv_obj_set_width(ui_TpsBar, 140);
    lv_obj_set_height(ui_TpsBar, 10);
    lv_obj_set_x(ui_TpsBar, 0);
    lv_obj_set_y(ui_TpsBar, 83);
    lv_obj_set_align(ui_TpsBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_TpsBar, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TpsBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TpsBar, lv_color_hex(0x06FF17), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TpsBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Arc5 = lv_arc_create(ui_MainScreen);
    lv_obj_set_width(ui_Arc5, 140);
    lv_obj_set_height(ui_Arc5, 140);
    lv_obj_set_x(ui_Arc5, 0);
    lv_obj_set_y(ui_Arc5, 170);
    lv_obj_set_align(ui_Arc5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc5, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_Arc5, 0);
    lv_obj_set_style_arc_width(ui_Arc5, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc5, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc5, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc5, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc5, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc5, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc5, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcValue5 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcValue5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcValue5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcValue5, 1);
    lv_obj_set_y(ui_ArcValue5, 165);
    lv_obj_set_align(ui_ArcValue5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcValue5, "---");
    lv_obj_set_style_text_font(ui_ArcValue5, &ui_font_ArameBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcUnit5 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcUnit5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcUnit5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcUnit5, -1);
    lv_obj_set_y(ui_ArcUnit5, 190);
    lv_obj_set_align(ui_ArcUnit5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcUnit5, "---");
    lv_obj_set_style_text_color(ui_ArcUnit5, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcUnit5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcUnit5, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcName5 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcName5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcName5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcName5, 0);
    lv_obj_set_y(ui_ArcName5, 217);
    lv_obj_set_align(ui_ArcName5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcName5, "---");
    lv_obj_set_style_text_font(ui_ArcName5, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcBG5 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_ArcBG5, &ui_img_arcscalenored_png);
    lv_obj_set_width(ui_ArcBG5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcBG5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcBG5, 0);
    lv_obj_set_y(ui_ArcBG5, 163);
    lv_obj_set_align(ui_ArcBG5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcBG5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ArcBG5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ArcBG5, 200);

    ui_MainAletPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_MainAletPanel, 140);
    lv_obj_set_height(ui_MainAletPanel, 250);
    lv_obj_set_x(ui_MainAletPanel, 0);
    lv_obj_set_y(ui_MainAletPanel, -30);
    lv_obj_set_align(ui_MainAletPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainAletPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_MainAletPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainAletPanel, lv_color_hex(0x2901D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainAletPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainAletPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainAletPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainAlertText = lv_label_create(ui_MainAletPanel);
    lv_obj_set_width(ui_MainAlertText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainAlertText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainAlertText, 1);
    lv_obj_set_y(ui_MainAlertText, -56);
    lv_obj_set_align(ui_MainAlertText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainAlertText, "LC\nON");
    lv_obj_set_style_text_align(ui_MainAlertText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainAlertText, &ui_font_ArameBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainLabelGear = lv_label_create(ui_MainAletPanel);
    lv_obj_set_width(ui_MainLabelGear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainLabelGear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainLabelGear, -1);
    lv_obj_set_y(ui_MainLabelGear, 60);
    lv_obj_set_align(ui_MainLabelGear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainLabelGear, "N");
    lv_obj_set_style_text_font(ui_MainLabelGear, &ui_font_ArameBold100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainAlertSpeed = lv_label_create(ui_MainAletPanel);
    lv_obj_set_width(ui_MainAlertSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainAlertSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainAlertSpeed, 0);
    lv_obj_set_y(ui_MainAlertSpeed, 107);
    lv_obj_set_align(ui_MainAlertSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainAlertSpeed, "080");
    lv_obj_set_style_text_font(ui_MainAlertSpeed, &ui_font_ArameBold30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_MainScreen);
    lv_obj_set_width(ui_Bar1, 190);
    lv_obj_set_height(ui_Bar1, 23);
    lv_obj_set_x(ui_Bar1, -250);
    lv_obj_set_y(ui_Bar1, -131);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarBG1 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_BarBG1, &ui_img_barscale_png);
    lv_obj_set_width(ui_BarBG1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarBG1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarBG1, -250);
    lv_obj_set_y(ui_BarBG1, -121);
    lv_obj_set_align(ui_BarBG1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BarBG1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BarBG1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarValue1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarValue1, -495);
    lv_obj_set_y(ui_BarValue1, -124);
    lv_obj_set_align(ui_BarValue1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BarValue1, "---");
    lv_obj_set_style_text_color(ui_BarValue1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BarValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BarValue1, &ui_font_ArameBold30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarUnit1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarUnit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarUnit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarUnit1, -495);
    lv_obj_set_y(ui_BarUnit1, -107);
    lv_obj_set_align(ui_BarUnit1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BarUnit1, "%");
    lv_obj_set_style_text_font(ui_BarUnit1, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarName1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarName1, 49);
    lv_obj_set_y(ui_BarName1, -108);
    lv_obj_set_align(ui_BarName1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BarName1, "---");
    lv_obj_set_style_text_font(ui_BarName1, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar2 = lv_bar_create(ui_MainScreen);
    lv_obj_set_width(ui_Bar2, 190);
    lv_obj_set_height(ui_Bar2, 23);
    lv_obj_set_x(ui_Bar2, 252);
    lv_obj_set_y(ui_Bar2, -130);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarBG2 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_BarBG2, &ui_img_barscale_png);
    lv_obj_set_width(ui_BarBG2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarBG2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarBG2, 253);
    lv_obj_set_y(ui_BarBG2, -120);
    lv_obj_set_align(ui_BarBG2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BarBG2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BarBG2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarName2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarName2, 552);
    lv_obj_set_y(ui_BarName2, -107);
    lv_obj_set_align(ui_BarName2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BarName2, "---");
    lv_obj_set_style_text_font(ui_BarName2, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarValue2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarValue2, 494);
    lv_obj_set_y(ui_BarValue2, -123);
    lv_obj_set_align(ui_BarValue2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BarValue2, "---");
    lv_obj_set_style_text_color(ui_BarValue2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BarValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BarValue2, &ui_font_ArameBold30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarUnit2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarUnit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarUnit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarUnit2, 497);
    lv_obj_set_y(ui_BarUnit2, -105);
    lv_obj_set_align(ui_BarUnit2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BarUnit2, "V");
    lv_obj_set_style_text_color(ui_BarUnit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BarUnit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BarUnit2, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc2 = lv_arc_create(ui_MainScreen);
    lv_obj_set_width(ui_Arc2, 140);
    lv_obj_set_height(ui_Arc2, 140);
    lv_obj_set_x(ui_Arc2, -150);
    lv_obj_set_y(ui_Arc2, -20);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_Arc2, 0);
    lv_obj_set_style_arc_width(ui_Arc2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc2, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcValue2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcValue2, -149);
    lv_obj_set_y(ui_ArcValue2, -22);
    lv_obj_set_align(ui_ArcValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcValue2, "---");
    lv_obj_set_style_text_color(ui_ArcValue2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcValue2, &ui_font_ArameBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcUnit2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcUnit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcUnit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcUnit2, -150);
    lv_obj_set_y(ui_ArcUnit2, 0);
    lv_obj_set_align(ui_ArcUnit2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcUnit2, "---");
    lv_obj_set_style_text_color(ui_ArcUnit2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcUnit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcUnit2, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcName2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcName2, -149);
    lv_obj_set_y(ui_ArcName2, 29);
    lv_obj_set_align(ui_ArcName2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcName2, "---\n---");
    lv_obj_set_style_text_align(ui_ArcName2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcName2, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcBG2 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_ArcBG2, &ui_img_arcscalerr_png);
    lv_obj_set_width(ui_ArcBG2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcBG2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcBG2, -150);
    lv_obj_set_y(ui_ArcBG2, -26);
    lv_obj_set_align(ui_ArcBG2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcBG2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ArcBG2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ArcBG2, 200);

    ui_Arc1 = lv_arc_create(ui_MainScreen);
    lv_obj_set_width(ui_Arc1, 140);
    lv_obj_set_height(ui_Arc1, 140);
    lv_obj_set_x(ui_Arc1, -300);
    lv_obj_set_y(ui_Arc1, -19);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_Arc1, 0);
    lv_obj_set_style_arc_width(ui_Arc1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcValue1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcValue1, -301);
    lv_obj_set_y(ui_ArcValue1, -22);
    lv_obj_set_align(ui_ArcValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcValue1, "---");
    lv_obj_set_style_text_color(ui_ArcValue1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcValue1, &ui_font_ArameBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcUnit1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcUnit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcUnit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcUnit1, -301);
    lv_obj_set_y(ui_ArcUnit1, 1);
    lv_obj_set_align(ui_ArcUnit1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcUnit1, "---");
    lv_obj_set_style_text_color(ui_ArcUnit1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcUnit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcUnit1, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcName1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcName1, -300);
    lv_obj_set_y(ui_ArcName1, 28);
    lv_obj_set_align(ui_ArcName1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcName1, "---\n---");
    lv_obj_set_style_text_align(ui_ArcName1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcName1, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcBG1 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_ArcBG1, &ui_img_arcscalerb_png);
    lv_obj_set_width(ui_ArcBG1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcBG1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcBG1, -300);
    lv_obj_set_y(ui_ArcBG1, -26);
    lv_obj_set_align(ui_ArcBG1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcBG1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ArcBG1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ArcBG1, 200);

    ui_Arc3 = lv_arc_create(ui_MainScreen);
    lv_obj_set_width(ui_Arc3, 140);
    lv_obj_set_height(ui_Arc3, 140);
    lv_obj_set_x(ui_Arc3, 150);
    lv_obj_set_y(ui_Arc3, -20);
    lv_obj_set_align(ui_Arc3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc3, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_Arc3, 0);
    lv_obj_set_style_arc_width(ui_Arc3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc3, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc3, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc3, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcValue3 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcValue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcValue3, 150);
    lv_obj_set_y(ui_ArcValue3, -22);
    lv_obj_set_align(ui_ArcValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcValue3, "---");
    lv_obj_set_style_text_color(ui_ArcValue3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcValue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcValue3, &ui_font_ArameBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcUnit3 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcUnit3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcUnit3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcUnit3, 150);
    lv_obj_set_y(ui_ArcUnit3, 1);
    lv_obj_set_align(ui_ArcUnit3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcUnit3, "°C");
    lv_obj_set_style_text_color(ui_ArcUnit3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcUnit3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcUnit3, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcName3 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcName3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcName3, 150);
    lv_obj_set_y(ui_ArcName3, 32);
    lv_obj_set_align(ui_ArcName3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcName3, "---\n---");
    lv_obj_set_style_text_align(ui_ArcName3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcName3, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcBG3 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_ArcBG3, &ui_img_arcscale_png);
    lv_obj_set_width(ui_ArcBG3, LV_SIZE_CONTENT);   /// -26
    lv_obj_set_height(ui_ArcBG3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcBG3, 150);
    lv_obj_set_y(ui_ArcBG3, -26);
    lv_obj_set_align(ui_ArcBG3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcBG3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ArcBG3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ArcBG3, 200);
    lv_obj_set_style_blend_mode(ui_ArcBG3, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc4 = lv_arc_create(ui_MainScreen);
    lv_obj_set_width(ui_Arc4, 140);
    lv_obj_set_height(ui_Arc4, 140);
    lv_obj_set_x(ui_Arc4, 300);
    lv_obj_set_y(ui_Arc4, -20);
    lv_obj_set_align(ui_Arc4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc4, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_Arc4, 0);
    lv_obj_set_style_arc_width(ui_Arc4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc4, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc4, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc4, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc4, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcValue4 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcValue4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcValue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcValue4, 300);
    lv_obj_set_y(ui_ArcValue4, -22);
    lv_obj_set_align(ui_ArcValue4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcValue4, "---");
    lv_obj_set_style_text_font(ui_ArcValue4, &ui_font_ArameBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcUnit4 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcUnit4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcUnit4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcUnit4, 300);
    lv_obj_set_y(ui_ArcUnit4, 1);
    lv_obj_set_align(ui_ArcUnit4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcUnit4, "---");
    lv_obj_set_style_text_color(ui_ArcUnit4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcUnit4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcUnit4, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcName4 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcName4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcName4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcName4, 300);
    lv_obj_set_y(ui_ArcName4, 32);
    lv_obj_set_align(ui_ArcName4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcName4, "---\n---");
    lv_obj_set_style_text_align(ui_ArcName4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcName4, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcBG4 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_ArcBG4, &ui_img_arcscale_png);
    lv_obj_set_width(ui_ArcBG4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcBG4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcBG4, 300);
    lv_obj_set_y(ui_ArcBG4, -27);
    lv_obj_set_align(ui_ArcBG4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcBG4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ArcBG4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ArcBG4, 200);

    ui_Panel1 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel1, 70);
    lv_obj_set_height(ui_Panel1, 41);
    lv_obj_set_x(ui_Panel1, -300);
    lv_obj_set_y(ui_Panel1, 76);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelValue1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_PanelValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PanelValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelValue1, "---");
    lv_obj_set_style_text_color(ui_PanelValue1, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PanelValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelValue1, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelName1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PanelName1, -300);
    lv_obj_set_y(ui_PanelName1, 96);
    lv_obj_set_align(ui_PanelName1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelName1, "---");
    lv_obj_set_style_text_font(ui_PanelName1, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelName1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelName1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelName1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelName1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelName1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel2, 70);
    lv_obj_set_height(ui_Panel2, 41);
    lv_obj_set_x(ui_Panel2, -225);
    lv_obj_set_y(ui_Panel2, 76);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelValue2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_PanelValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PanelValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelValue2, "---");
    lv_obj_set_style_text_color(ui_PanelValue2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PanelValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelValue2, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelName2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PanelName2, -225);
    lv_obj_set_y(ui_PanelName2, 96);
    lv_obj_set_align(ui_PanelName2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelName2, "---");
    lv_obj_set_style_text_font(ui_PanelName2, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelName2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelName2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelName2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelName2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelName2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel3, 70);
    lv_obj_set_height(ui_Panel3, 41);
    lv_obj_set_x(ui_Panel3, -150);
    lv_obj_set_y(ui_Panel3, 76);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelValue3 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_PanelValue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PanelValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelValue3, "---");
    lv_obj_set_style_text_color(ui_PanelValue3, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PanelValue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelValue3, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelName3 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelName3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PanelName3, -150);
    lv_obj_set_y(ui_PanelName3, 95);
    lv_obj_set_align(ui_PanelName3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelName3, "---");
    lv_obj_set_style_text_font(ui_PanelName3, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelName3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelName3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelName3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelName3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelName3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel4, 70);
    lv_obj_set_height(ui_Panel4, 41);
    lv_obj_set_x(ui_Panel4, 150);
    lv_obj_set_y(ui_Panel4, 76);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelValue4 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_PanelValue4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelValue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PanelValue4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelValue4, "---");
    lv_obj_set_style_text_color(ui_PanelValue4, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PanelValue4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelValue4, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelName4 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelName4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelName4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PanelName4, 150);
    lv_obj_set_y(ui_PanelName4, 95);
    lv_obj_set_align(ui_PanelName4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelName4, "---");
    lv_obj_set_style_text_font(ui_PanelName4, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelName4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelName4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelName4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelName4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelName4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel5, 70);
    lv_obj_set_height(ui_Panel5, 41);
    lv_obj_set_x(ui_Panel5, 225);
    lv_obj_set_y(ui_Panel5, 76);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelValue5 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_PanelValue5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelValue5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PanelValue5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelValue5, "---");
    lv_obj_set_style_text_color(ui_PanelValue5, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PanelValue5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelValue5, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelName5 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelName5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelName5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PanelName5, 225);
    lv_obj_set_y(ui_PanelName5, 95);
    lv_obj_set_align(ui_PanelName5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelName5, "---");
    lv_obj_set_style_text_font(ui_PanelName5, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelName5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelName5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelName5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelName5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelName5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel6, 70);
    lv_obj_set_height(ui_Panel6, 41);
    lv_obj_set_x(ui_Panel6, 300);
    lv_obj_set_y(ui_Panel6, 76);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelValue6 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_PanelValue6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelValue6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PanelValue6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelValue6, "---");
    lv_obj_set_style_text_color(ui_PanelValue6, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PanelValue6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelValue6, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelName6 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelName6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelName6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PanelName6, 300);
    lv_obj_set_y(ui_PanelName6, 95);
    lv_obj_set_align(ui_PanelName6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelName6, "---");
    lv_obj_set_style_text_font(ui_PanelName6, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelName6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelName6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelName6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelName6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelName6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar3 = lv_bar_create(ui_MainScreen);
    lv_obj_set_width(ui_Bar3, 190);
    lv_obj_set_height(ui_Bar3, 23);
    lv_obj_set_x(ui_Bar3, -225);
    lv_obj_set_y(ui_Bar3, 122);
    lv_obj_set_align(ui_Bar3, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarBG3 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_BarBG3, &ui_img_barscalerb_png);
    lv_obj_set_width(ui_BarBG3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarBG3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarBG3, -225);
    lv_obj_set_y(ui_BarBG3, 132);
    lv_obj_set_align(ui_BarBG3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BarBG3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BarBG3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_BarBG3, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarName3 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarName3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarName3, -524);
    lv_obj_set_y(ui_BarName3, 148);
    lv_obj_set_align(ui_BarName3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BarName3, "---");
    lv_obj_set_style_text_font(ui_BarName3, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarValue3 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarValue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarValue3, -690);
    lv_obj_set_y(ui_BarValue3, 151);
    lv_obj_set_align(ui_BarValue3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BarValue3, "---");
    lv_obj_set_style_text_color(ui_BarValue3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BarValue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BarValue3, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarUnit3 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarUnit3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarUnit3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarUnit3, 112);
    lv_obj_set_y(ui_BarUnit3, 149);
    lv_obj_set_align(ui_BarUnit3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BarUnit3, "---");
    lv_obj_set_style_text_color(ui_BarUnit3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BarUnit3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BarUnit3, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar4 = lv_bar_create(ui_MainScreen);
    lv_obj_set_width(ui_Bar4, 190);
    lv_obj_set_height(ui_Bar4, 23);
    lv_obj_set_x(ui_Bar4, 225);
    lv_obj_set_y(ui_Bar4, 122);
    lv_obj_set_align(ui_Bar4, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarBG4 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_BarBG4, &ui_img_barscalered_png);
    lv_obj_set_width(ui_BarBG4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarBG4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarBG4, 225);
    lv_obj_set_y(ui_BarBG4, 132);
    lv_obj_set_align(ui_BarBG4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BarBG4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BarBG4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_BarBG4, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarName4 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarName4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarName4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarName4, -74);
    lv_obj_set_y(ui_BarName4, 150);
    lv_obj_set_align(ui_BarName4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BarName4, "---");
    lv_obj_set_style_text_font(ui_BarName4, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarValue4 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarValue4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarValue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarValue4, -239);
    lv_obj_set_y(ui_BarValue4, 153);
    lv_obj_set_align(ui_BarValue4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BarValue4, "---");
    lv_obj_set_style_text_color(ui_BarValue4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BarValue4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BarValue4, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarUnit4 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarUnit4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarUnit4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarUnit4, 562);
    lv_obj_set_y(ui_BarUnit4, 154);
    lv_obj_set_align(ui_BarUnit4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BarUnit4, "---");
    lv_obj_set_style_text_color(ui_BarUnit4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BarUnit4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BarUnit4, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button1, 113);
    lv_obj_set_height(ui_Button1, 51);
    lv_obj_set_x(ui_Button1, 331);
    lv_obj_set_y(ui_Button1, 203);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xAD0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonLabel1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ButtonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ButtonLabel1, 333);
    lv_obj_set_y(ui_ButtonLabel1, 204);
    lv_obj_set_align(ui_ButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonLabel1, "START\nSTOP");
    lv_obj_set_style_text_align(ui_ButtonLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonLabel1, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CriticalAlertPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_CriticalAlertPanel, 523);
    lv_obj_set_height(ui_CriticalAlertPanel, 247);
    lv_obj_set_x(ui_CriticalAlertPanel, 1);
    lv_obj_set_y(ui_CriticalAlertPanel, -9);
    lv_obj_set_align(ui_CriticalAlertPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CriticalAlertPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_CriticalAlertPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CriticalAlertPanel, lv_color_hex(0xD80000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CriticalAlertPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CriticalAlertText = lv_label_create(ui_CriticalAlertPanel);
    lv_obj_set_width(ui_CriticalAlertText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CriticalAlertText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CriticalAlertText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CriticalAlertText, "OIL PRESSURE\nLOW");
    lv_obj_set_style_text_color(ui_CriticalAlertText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CriticalAlertText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CriticalAlertText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CriticalAlertText, &ui_font_ArameBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button2, 79);
    lv_obj_set_height(ui_Button2, 40);
    lv_obj_set_x(ui_Button2, 229);
    lv_obj_set_y(ui_Button2, 209);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x092C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonLabel2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ButtonLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ButtonLabel2, 230);
    lv_obj_set_y(ui_ButtonLabel2, 210);
    lv_obj_set_align(ui_ButtonLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonLabel2, "DATALOG\nOFF");
    lv_obj_add_flag(ui_ButtonLabel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_align(ui_ButtonLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonLabel2, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClockLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ClockLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel, -236);
    lv_obj_set_y(ui_ClockLabel, 220);
    lv_obj_set_align(ui_ClockLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLabel, "--:-- -- | ------ | ---- msnm");
    lv_obj_set_style_text_font(ui_ClockLabel, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ClockLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ClockLabel, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClockLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ClockLabel, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ClockLabel, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ClockLabel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ClockLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button3, 79);
    lv_obj_set_height(ui_Button3, 40);
    lv_obj_set_x(ui_Button3, 143);
    lv_obj_set_y(ui_Button3, 209);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x00013C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonLabel3 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ButtonLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ButtonLabel3, 144);
    lv_obj_set_y(ui_ButtonLabel3, 210);
    lv_obj_set_align(ui_ButtonLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonLabel3, "LAUCH\nOFF");
    lv_obj_add_flag(ui_ButtonLabel3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_align(ui_ButtonLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonLabel3, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_ConfigPanel, 315);
    lv_obj_set_height(ui_ConfigPanel, 330);
    lv_obj_set_x(ui_ConfigPanel, -236);
    lv_obj_set_y(ui_ConfigPanel, 72);
    lv_obj_set_align(ui_ConfigPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ConfigPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConfigPanel, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConfigPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConfigPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConfigPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigName = lv_textarea_create(ui_ConfigPanel);
    lv_obj_set_width(ui_ConfigName, 315);
    lv_obj_set_height(ui_ConfigName, LV_SIZE_CONTENT);    /// 34
    lv_obj_set_x(ui_ConfigName, -1);
    lv_obj_set_y(ui_ConfigName, -144);
    lv_obj_set_align(ui_ConfigName, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_ConfigName, "--------");
    lv_textarea_set_placeholder_text(ui_ConfigName, "Placeholder...");
    lv_textarea_set_one_line(ui_ConfigName, true);
    lv_obj_clear_flag(ui_ConfigName, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_ConfigName, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfigName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ConfigName, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfigName, &ui_font_ArameBold30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfigName, lv_color_hex(0xFFCE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConfigName, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConfigName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConfigName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConfigName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConfigName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConfigName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ConfigExit = lv_btn_create(ui_ConfigName);
    lv_obj_set_width(ui_ConfigExit, 30);
    lv_obj_set_height(ui_ConfigExit, 29);
    lv_obj_set_x(ui_ConfigExit, 136);
    lv_obj_set_y(ui_ConfigExit, 0);
    lv_obj_set_align(ui_ConfigExit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigExit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfigExit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConfigExit, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfigExit, lv_color_hex(0x080C08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ConfigExit, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConfigExit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ConfigExit, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_ConfigExit);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -1);
    lv_obj_set_y(ui_Label7, 1);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "X");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFCE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GaugeType = lv_dropdown_create(ui_ConfigPanel);
    lv_obj_set_width(ui_GaugeType, 185);
    lv_obj_set_height(ui_GaugeType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GaugeType, 49);
    lv_obj_set_y(ui_GaugeType, -94);
    lv_obj_set_align(ui_GaugeType, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GaugeType, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_GaugeType, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GaugeType, lv_color_hex(0x080C08), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GaugeType, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GaugeType, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_GaugeType, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_GaugeType), &ui_font_ArameBold14,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_GaugeType), lv_color_hex(0x080C08),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_GaugeType), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_GaugeType), lv_color_hex(0x000000),
                                LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_GaugeType), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_GaugeType), lv_color_hex(0xE3D302),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_GaugeType), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_GaugeType), lv_color_hex(0x000000),
                                LV_PART_SELECTED | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_GaugeType), 255,  LV_PART_SELECTED | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_GaugeType), lv_color_hex(0xE3D302),
                              LV_PART_SELECTED | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_GaugeType), 255,  LV_PART_SELECTED | LV_STATE_CHECKED);

    ui_HWASlider = lv_slider_create(ui_ConfigPanel);
    lv_slider_set_range(ui_HWASlider, 1000, 10000);
    lv_slider_set_value(ui_HWASlider, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_HWASlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_HWASlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_HWASlider, 280);
    lv_obj_set_height(ui_HWASlider, 10);
    lv_obj_set_x(ui_HWASlider, 0);
    lv_obj_set_y(ui_HWASlider, -27);
    lv_obj_set_align(ui_HWASlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_HWASlider, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HWASlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_HWASlider, lv_color_hex(0xFFFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HWASlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_HWASlider, lv_color_hex(0xFFFF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HWASlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HWASlider, lv_color_hex(0x404040), LV_PART_KNOB | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_HWASlider, 255, LV_PART_KNOB | LV_STATE_DISABLED);

    ui_HDASlider = lv_slider_create(ui_ConfigPanel);
    lv_slider_set_range(ui_HDASlider, 5000, 10000);
    lv_slider_set_value(ui_HDASlider, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_HDASlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_HDASlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_HDASlider, 280);
    lv_obj_set_height(ui_HDASlider, 10);
    lv_obj_set_x(ui_HDASlider, 0);
    lv_obj_set_y(ui_HDASlider, 17);
    lv_obj_set_align(ui_HDASlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_HDASlider, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HDASlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_HDASlider, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HDASlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_HDASlider, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HDASlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HDASlider, lv_color_hex(0x404040), LV_PART_KNOB | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_HDASlider, 255, LV_PART_KNOB | LV_STATE_DISABLED);

    ui_LWASlider = lv_slider_create(ui_ConfigPanel);
    lv_slider_set_range(ui_LWASlider, 1000, 10000);
    lv_slider_set_value(ui_LWASlider, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_LWASlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_LWASlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_LWASlider, 280);
    lv_obj_set_height(ui_LWASlider, 10);
    lv_obj_set_x(ui_LWASlider, 0);
    lv_obj_set_y(ui_LWASlider, 62);
    lv_obj_set_align(ui_LWASlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_LWASlider, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LWASlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LWASlider, lv_color_hex(0xFFFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LWASlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LWASlider, lv_color_hex(0xFFFF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LWASlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LWASlider, lv_color_hex(0x404040), LV_PART_KNOB | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_LWASlider, 255, LV_PART_KNOB | LV_STATE_DISABLED);

    ui_LDASlider = lv_slider_create(ui_ConfigPanel);
    lv_slider_set_range(ui_LDASlider, 5000, 10000);
    lv_slider_set_value(ui_LDASlider, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_LDASlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_LDASlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_LDASlider, 280);
    lv_obj_set_height(ui_LDASlider, 10);
    lv_obj_set_x(ui_LDASlider, 0);
    lv_obj_set_y(ui_LDASlider, 103);
    lv_obj_set_align(ui_LDASlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_LDASlider, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LDASlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LDASlider, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LDASlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LDASlider, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LDASlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LDASlider, lv_color_hex(0x404040), LV_PART_KNOB | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_LDASlider, 255, LV_PART_KNOB | LV_STATE_DISABLED);

    ui_HWALabel = lv_label_create(ui_ConfigPanel);
    lv_obj_set_width(ui_HWALabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HWALabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HWALabel, 126);
    lv_obj_set_y(ui_HWALabel, -51);
    lv_obj_set_align(ui_HWALabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HWALabel, "0");
    lv_obj_set_style_text_font(ui_HWALabel, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_HWALabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_HWALabel, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_HDALabel = lv_label_create(ui_ConfigPanel);
    lv_obj_set_width(ui_HDALabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HDALabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HDALabel, 125);
    lv_obj_set_y(ui_HDALabel, -3);
    lv_obj_set_align(ui_HDALabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HDALabel, "0");
    lv_obj_set_style_text_font(ui_HDALabel, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_HDALabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_HDALabel, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_LWALabel = lv_label_create(ui_ConfigPanel);
    lv_obj_set_width(ui_LWALabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LWALabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LWALabel, 126);
    lv_obj_set_y(ui_LWALabel, 43);
    lv_obj_set_align(ui_LWALabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LWALabel, "0");
    lv_obj_set_style_text_font(ui_LWALabel, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LWALabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_LWALabel, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_LDALabel = lv_label_create(ui_ConfigPanel);
    lv_obj_set_width(ui_LDALabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LDALabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LDALabel, 126);
    lv_obj_set_y(ui_LDALabel, 85);
    lv_obj_set_align(ui_LDALabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LDALabel, "0");
    lv_obj_set_style_text_font(ui_LDALabel, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LDALabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_LDALabel, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_ConfigText = lv_label_create(ui_ConfigPanel);
    lv_obj_set_width(ui_ConfigText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfigText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConfigText, 16);
    lv_obj_set_y(ui_ConfigText, 41);
    lv_label_set_text(ui_ConfigText, "------\n\n------\n\n------\n\n------\n\n------");
    lv_obj_clear_flag(ui_ConfigText, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_ConfigText, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_letter_space(ui_ConfigText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_ConfigText, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfigText, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlertCheck = lv_checkbox_create(ui_ConfigPanel);
    lv_checkbox_set_text(ui_AlertCheck, "ENABLE ALERT");
    lv_obj_set_width(ui_AlertCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlertCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlertCheck, -78);
    lv_obj_set_y(ui_AlertCheck, 136);
    lv_obj_set_align(ui_AlertCheck, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AlertCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_AlertCheck, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_AlertCheck, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_text_opa(ui_AlertCheck, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_set_style_border_color(ui_AlertCheck, lv_color_hex(0xFFCE00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AlertCheck, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AlertCheck, lv_color_hex(0xB18F00), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_AlertCheck, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_AlertCheck, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DISABLED);
    lv_obj_set_style_border_opa(ui_AlertCheck, 255, LV_PART_INDICATOR | LV_STATE_DISABLED);

    ui_SaveBTN = lv_btn_create(ui_ConfigPanel);
    lv_obj_set_height(ui_SaveBTN, 29);
    lv_obj_set_width(ui_SaveBTN, LV_SIZE_CONTENT);   /// 127
    lv_obj_set_x(ui_SaveBTN, 69);
    lv_obj_set_y(ui_SaveBTN, 135);
    lv_obj_set_align(ui_SaveBTN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SaveBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SaveBTN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SaveBTN, lv_color_hex(0xE3D302), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SaveBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SaveBTN, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveBTN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SaveBTN, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_SaveBTN);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "sAVE sETTINGS");

    ui_ClockLabel1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ClockLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel1, -236);
    lv_obj_set_y(ui_ClockLabel1, 185);
    lv_obj_set_align(ui_ClockLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLabel1, "Trip a | 1.145 km");
    lv_obj_set_style_text_font(ui_ClockLabel1, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ClockLabel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ClockLabel1, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClockLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ClockLabel1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ClockLabel1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ClockLabel1, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ClockLabel1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Menu1 = lv_roller_create(ui_MainScreen);
    lv_roller_set_options(ui_Menu1,
                          "POPS & BANGS\nLAUNCH\nDATALOG\nQUICKSHIFT\nRIDING MODE\nTRIP A\nTRIP B\nTRIP INFO\nSERVICE\nSECURITY\nEXIT",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_Menu1, 4, LV_ANIM_OFF);
    lv_obj_set_height(ui_Menu1, 480);
    lv_obj_set_width(ui_Menu1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_Menu1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Menu1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_align(ui_Menu1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Menu1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Menu1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu1, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Menu1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Menu1, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Menu1, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_text_color(ui_Menu1, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Menu1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Menu1, lv_color_hex(0xFFCE00), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Menu2 = lv_roller_create(ui_MainScreen);
    lv_roller_set_options(ui_Menu2, "Option 1\nOption 2\nOption 3\nOption 4\nOption 5\nOption 6", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_Menu2, 480);
    lv_obj_set_width(ui_Menu2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Menu2, 152);
    lv_obj_set_y(ui_Menu2, 0);
    lv_obj_set_align(ui_Menu2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Menu2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_Menu2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Menu2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu2, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Menu2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Menu2, 230, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Menu2, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Menu2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Menu2, lv_color_hex(0xFFCE00), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel7, 631);
    lv_obj_set_height(ui_Panel7, 441);
    lv_obj_set_x(ui_Panel7, 67);
    lv_obj_set_y(ui_Panel7, 2);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel7, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_add_flag(ui_Panel7, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 240, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel7, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel7, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel7, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label1, 180);
    lv_obj_set_height(ui_Label1, 80);
    lv_obj_set_x(ui_Label1, -203);
    lv_obj_set_y(ui_Label1, -137);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label1, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label1, "1356.3");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_ArameBold50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label1, lv_color_hex(0xFFCE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Label1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 1);
    lv_obj_set_y(ui_Label3, 31);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "TOTAL TRIP KM");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label2, 180);
    lv_obj_set_height(ui_Label2, 80);
    lv_obj_set_x(ui_Label2, -6);
    lv_obj_set_y(ui_Label2, -137);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label2, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label2, "12:03");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_ArameBold50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label2, lv_color_hex(0xFFCE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Label2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 1);
    lv_obj_set_y(ui_Label4, 31);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "TOTAL TIME");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label8, 180);
    lv_obj_set_height(ui_Label8, 80);
    lv_obj_set_x(ui_Label8, -6);
    lv_obj_set_y(ui_Label8, -137);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label8, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label8, "5.3");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_ArameBold50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label8, lv_color_hex(0xFFCE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label8, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label8, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Label8);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 1);
    lv_obj_set_y(ui_Label10, 31);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "USED FUEL GAL");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label11, 180);
    lv_obj_set_height(ui_Label11, 80);
    lv_obj_set_x(ui_Label11, -6);
    lv_obj_set_y(ui_Label11, -137);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label11, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label11, "150.3");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_ArameBold50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label11, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label11, lv_color_hex(0xFFCE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label11, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label11, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label11, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label11, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Label11);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 1);
    lv_obj_set_y(ui_Label12, 31);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "SESSION KM");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label13, 180);
    lv_obj_set_height(ui_Label13, 80);
    lv_obj_set_x(ui_Label13, -6);
    lv_obj_set_y(ui_Label13, -137);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label13, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label13, "00:30");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_ArameBold50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label13, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label13, lv_color_hex(0xFFCE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label13, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label13, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label13, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label13, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Label13);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 1);
    lv_obj_set_y(ui_Label14, 31);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "SESSION TIME");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label15, 180);
    lv_obj_set_height(ui_Label15, 80);
    lv_obj_set_x(ui_Label15, -6);
    lv_obj_set_y(ui_Label15, -137);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label15, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_Label15, "120.3");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label15, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_ArameBold50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label15, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label15, lv_color_hex(0xFFCE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label15, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label15, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label15, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label15, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Label15);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 1);
    lv_obj_set_y(ui_Label16, 31);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "KM/GAL");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart1 = lv_chart_create(ui_Panel7);
    lv_obj_set_width(ui_Chart1, 491);
    lv_obj_set_height(ui_Chart1, 177);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart1, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 25, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 0, 0, false, 25);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xFFCE00),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 0, 5, 12, 18, 25, 32, 28, 35, 41, 48, 54, 61, 67, 74, 80, 76, 83, 89, 95, 92, 88, 84, 79, 73, 68, 63, 57, 51, 46, 40, 35, 30, 25, 20, 16, 12, 9, 6, 12, 18, 25, 31, 38, 44, 51, 57, 64, 70, 77, 83, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);
    lv_obj_set_style_bg_color(ui_Chart1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_line_color(ui_Chart1, lv_color_hex(0xFF0000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart1, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);


    ui_LeftArrow = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_LeftArrow, &ui_img_leftarrow_png);
    lv_obj_set_width(ui_LeftArrow, LV_SIZE_CONTENT);   /// 238
    lv_obj_set_height(ui_LeftArrow, LV_SIZE_CONTENT);    /// 222
    lv_obj_set_x(ui_LeftArrow, -278);
    lv_obj_set_y(ui_LeftArrow, -67);
    lv_obj_set_align(ui_LeftArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LeftArrow, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LeftArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_LeftArrow, lv_color_hex(0x0FB201), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_LeftArrow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_LeftArrow, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RightArrow = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_RightArrow, &ui_img_righarrow_png);
    lv_obj_set_width(ui_RightArrow, LV_SIZE_CONTENT);   /// 236
    lv_obj_set_height(ui_RightArrow, LV_SIZE_CONTENT);    /// 222
    lv_obj_set_x(ui_RightArrow, 447);
    lv_obj_set_y(ui_RightArrow, -67);
    lv_obj_set_align(ui_RightArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RightArrow, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RightArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_RightArrow, lv_color_hex(0x0FB201), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_RightArrow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_RightArrow, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LowBean = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_LowBean, &ui_img_lowbean_png);
    lv_obj_set_width(ui_LowBean, LV_SIZE_CONTENT);   /// 516
    lv_obj_set_height(ui_LowBean, LV_SIZE_CONTENT);    /// 428
    lv_obj_set_x(ui_LowBean, 347);
    lv_obj_set_y(ui_LowBean, 397);
    lv_obj_set_align(ui_LowBean, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LowBean, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LowBean, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_LowBean, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_LowBean, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_LowBean, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HighBean = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_HighBean, &ui_img_highbean_png);
    lv_obj_set_width(ui_HighBean, LV_SIZE_CONTENT);   /// 504
    lv_obj_set_height(ui_HighBean, LV_SIZE_CONTENT);    /// 370
    lv_obj_set_x(ui_HighBean, 404);
    lv_obj_set_y(ui_HighBean, 372);
    lv_obj_set_align(ui_HighBean, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HighBean, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HighBean, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_HighBean, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_HighBean, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_HighBean, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FogLight = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_FogLight, &ui_img_foglight_png);
    lv_obj_set_width(ui_FogLight, LV_SIZE_CONTENT);   /// 458
    lv_obj_set_height(ui_FogLight, LV_SIZE_CONTENT);    /// 383
    lv_obj_set_x(ui_FogLight, 444);
    lv_obj_set_y(ui_FogLight, 376);
    lv_obj_set_align(ui_FogLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FogLight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FogLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_FogLight, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_FogLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_FogLight, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CoolantLvl = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_CoolantLvl, &ui_img_coolant_png);
    lv_obj_set_width(ui_CoolantLvl, LV_SIZE_CONTENT);   /// 543
    lv_obj_set_height(ui_CoolantLvl, LV_SIZE_CONTENT);    /// 384
    lv_obj_set_x(ui_CoolantLvl, 17);
    lv_obj_set_y(ui_CoolantLvl, 79);
    lv_obj_set_align(ui_CoolantLvl, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CoolantLvl, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CoolantLvl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_CoolantLvl, lv_color_hex(0xE00606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_CoolantLvl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_CoolantLvl, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ArcBG5, ui_event_ArcBG5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcBG2, ui_event_ArcBG2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcBG1, ui_event_ArcBG1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcBG3, ui_event_ArcBG3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ArcBG4, ui_event_ArcBG4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConfigExit, ui_event_ConfigExit, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_GaugeType, ui_event_GaugeType, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HWASlider, ui_event_HWASlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HDASlider, ui_event_HDASlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LWASlider, ui_event_LWASlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LDASlider, ui_event_LDASlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Menu1, ui_event_Menu1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Menu2, ui_event_Menu2, LV_EVENT_ALL, NULL);

}
