// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: ADVdash

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RpmsBG = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_RpmsBG, &ui_img_rpmscalev3t_png);
    lv_obj_set_width(ui_RpmsBG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RpmsBG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RpmsBG, -87);
    lv_obj_set_y(ui_RpmsBG, -203);
    lv_obj_set_align(ui_RpmsBG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RpmsBG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RpmsBG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RedLineBar = lv_bar_create(ui_MainScreen);
    lv_bar_set_mode(ui_RedLineBar, LV_BAR_MODE_RANGE);
    lv_bar_set_value(ui_RedLineBar, 100, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_RedLineBar, 20, LV_ANIM_OFF);
    lv_obj_set_width(ui_RedLineBar, 310);
    lv_obj_set_height(ui_RedLineBar, 30);
    lv_obj_set_x(ui_RedLineBar, 62);
    lv_obj_set_y(ui_RedLineBar, -190);
    lv_obj_set_align(ui_RedLineBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_RedLineBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RedLineBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RedLineBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RedLineBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RedLineBar, lv_color_hex(0xFF0303), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RedLineBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_RedLineBar, LV_BLEND_MODE_MULTIPLY, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_RpmsBar = lv_bar_create(ui_MainScreen);
    lv_bar_set_range(ui_RpmsBar, 0, 1000);
    lv_obj_set_width(ui_RpmsBar, 597);
    lv_obj_set_height(ui_RpmsBar, 30);
    lv_obj_set_x(ui_RpmsBar, -88);
    lv_obj_set_y(ui_RpmsBar, -209);
    lv_obj_set_align(ui_RpmsBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_RpmsBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RpmsBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RpmsBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RpmsBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RpmsBar, lv_color_hex(0xDCDCDC), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RpmsBar, 250, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RpmsBar, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RpmsBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RpmsBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_RpmsBar, LV_BORDER_SIDE_NONE, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_RpmsValue = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_RpmsValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RpmsValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RpmsValue, -29);
    lv_obj_set_y(ui_RpmsValue, -198);
    lv_obj_set_align(ui_RpmsValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_RpmsValue, "0");
    lv_obj_set_style_text_align(ui_RpmsValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RpmsValue, &ui_font_ArameBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RpmsText = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_RpmsText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RpmsText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RpmsText, 352);
    lv_obj_set_y(ui_RpmsText, -173);
    lv_obj_set_align(ui_RpmsText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RpmsText, "RPMS");
    lv_obj_set_style_text_font(ui_RpmsText, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GearPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_GearPanel, 140);
    lv_obj_set_height(ui_GearPanel, 174);
    lv_obj_set_x(ui_GearPanel, 0);
    lv_obj_set_y(ui_GearPanel, -14);
    lv_obj_set_align(ui_GearPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GearPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_GearPanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_GearPanel, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GearPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GearPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GearPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GearValue = lv_label_create(ui_GearPanel);
    lv_obj_set_width(ui_GearValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GearValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GearValue, 0);
    lv_obj_set_y(ui_GearValue, 5);
    lv_obj_set_align(ui_GearValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GearValue, "N");
    lv_obj_set_style_text_font(ui_GearValue, &ui_font_ArameBold150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_SpeedPanel, 140);
    lv_obj_set_height(ui_SpeedPanel, 50);
    lv_obj_set_x(ui_SpeedPanel, 0);
    lv_obj_set_y(ui_SpeedPanel, -128);
    lv_obj_set_align(ui_SpeedPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpeedPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_SpeedPanel, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_SpeedPanel, lv_color_hex(0xC4C4C4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeedPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SpeedPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SpeedPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeedValue = lv_label_create(ui_SpeedPanel);
    lv_obj_set_width(ui_SpeedValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeedValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SpeedValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SpeedValue, "---");
    lv_obj_set_style_text_color(ui_SpeedValue, lv_color_hex(0x020202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpeedValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpeedValue, &ui_font_ArameBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TpsBar = lv_bar_create(ui_MainScreen);
    lv_bar_set_range(ui_TpsBar, 0, 10000);
    lv_obj_set_width(ui_TpsBar, 140);
    lv_obj_set_height(ui_TpsBar, 10);
    lv_obj_set_x(ui_TpsBar, 0);
    lv_obj_set_y(ui_TpsBar, 83);
    lv_obj_set_align(ui_TpsBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_TpsBar, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TpsBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TpsBar, lv_color_hex(0x06FF17), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TpsBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Arc5 = lv_arc_create(ui_MainScreen);
    lv_obj_set_width(ui_Arc5, 140);
    lv_obj_set_height(ui_Arc5, 140);
    lv_obj_set_x(ui_Arc5, 0);
    lv_obj_set_y(ui_Arc5, 170);
    lv_obj_set_align(ui_Arc5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc5, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_Arc5, 0);
    lv_obj_set_style_arc_width(ui_Arc5, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc5, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc5, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc5, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc5, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc5, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc5, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcValue5 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcValue5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcValue5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcValue5, 1);
    lv_obj_set_y(ui_ArcValue5, 165);
    lv_obj_set_align(ui_ArcValue5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcValue5, "---");
    lv_obj_set_style_text_font(ui_ArcValue5, &ui_font_ArameBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcUnit5 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcUnit5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcUnit5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcUnit5, -1);
    lv_obj_set_y(ui_ArcUnit5, 190);
    lv_obj_set_align(ui_ArcUnit5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcUnit5, "---");
    lv_obj_set_style_text_color(ui_ArcUnit5, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcUnit5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcUnit5, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcName5 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcName5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcName5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcName5, 0);
    lv_obj_set_y(ui_ArcName5, 217);
    lv_obj_set_align(ui_ArcName5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcName5, "---");
    lv_obj_set_style_text_font(ui_ArcName5, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcBG5 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_ArcBG5, &ui_img_arcscalenored_png);
    lv_obj_set_width(ui_ArcBG5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcBG5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcBG5, 0);
    lv_obj_set_y(ui_ArcBG5, 163);
    lv_obj_set_align(ui_ArcBG5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcBG5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ArcBG5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ArcBG5, 200);

    ui_MainAletPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_MainAletPanel, 140);
    lv_obj_set_height(ui_MainAletPanel, 250);
    lv_obj_set_x(ui_MainAletPanel, 0);
    lv_obj_set_y(ui_MainAletPanel, -30);
    lv_obj_set_align(ui_MainAletPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MainAletPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_MainAletPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainAletPanel, lv_color_hex(0x2901D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainAletPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainAletPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainAletPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainAlertText = lv_label_create(ui_MainAletPanel);
    lv_obj_set_width(ui_MainAlertText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainAlertText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainAlertText, 1);
    lv_obj_set_y(ui_MainAlertText, -56);
    lv_obj_set_align(ui_MainAlertText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainAlertText, "LC\nON");
    lv_obj_set_style_text_align(ui_MainAlertText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainAlertText, &ui_font_ArameBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainLabelGear = lv_label_create(ui_MainAletPanel);
    lv_obj_set_width(ui_MainLabelGear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainLabelGear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainLabelGear, -1);
    lv_obj_set_y(ui_MainLabelGear, 60);
    lv_obj_set_align(ui_MainLabelGear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainLabelGear, "N");
    lv_obj_set_style_text_font(ui_MainLabelGear, &ui_font_ArameBold100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainAlertSpeed = lv_label_create(ui_MainAletPanel);
    lv_obj_set_width(ui_MainAlertSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainAlertSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainAlertSpeed, 0);
    lv_obj_set_y(ui_MainAlertSpeed, 107);
    lv_obj_set_align(ui_MainAlertSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainAlertSpeed, "080");
    lv_obj_set_style_text_font(ui_MainAlertSpeed, &ui_font_ArameBold30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_MainScreen);
    lv_obj_set_width(ui_Bar1, 190);
    lv_obj_set_height(ui_Bar1, 23);
    lv_obj_set_x(ui_Bar1, -250);
    lv_obj_set_y(ui_Bar1, -141);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarBG1 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_BarBG1, &ui_img_barscale_png);
    lv_obj_set_width(ui_BarBG1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarBG1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarBG1, -250);
    lv_obj_set_y(ui_BarBG1, -131);
    lv_obj_set_align(ui_BarBG1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BarBG1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BarBG1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarValue1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarValue1, -495);
    lv_obj_set_y(ui_BarValue1, -134);
    lv_obj_set_align(ui_BarValue1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BarValue1, "---");
    lv_obj_set_style_text_color(ui_BarValue1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BarValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BarValue1, &ui_font_ArameBold30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarUnit1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarUnit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarUnit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarUnit1, -495);
    lv_obj_set_y(ui_BarUnit1, -117);
    lv_obj_set_align(ui_BarUnit1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BarUnit1, "%");
    lv_obj_set_style_text_font(ui_BarUnit1, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarName1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarName1, 49);
    lv_obj_set_y(ui_BarName1, -118);
    lv_obj_set_align(ui_BarName1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BarName1, "---");
    lv_obj_set_style_text_font(ui_BarName1, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar2 = lv_bar_create(ui_MainScreen);
    lv_bar_set_value(ui_Bar2, 60, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 190);
    lv_obj_set_height(ui_Bar2, 23);
    lv_obj_set_x(ui_Bar2, 252);
    lv_obj_set_y(ui_Bar2, -140);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarBG2 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_BarBG2, &ui_img_barscale_png);
    lv_obj_set_width(ui_BarBG2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarBG2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarBG2, 253);
    lv_obj_set_y(ui_BarBG2, -130);
    lv_obj_set_align(ui_BarBG2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BarBG2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BarBG2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarName2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarName2, 552);
    lv_obj_set_y(ui_BarName2, -117);
    lv_obj_set_align(ui_BarName2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BarName2, "---");
    lv_obj_set_style_text_font(ui_BarName2, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarValue2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarValue2, 494);
    lv_obj_set_y(ui_BarValue2, -133);
    lv_obj_set_align(ui_BarValue2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BarValue2, "---");
    lv_obj_set_style_text_color(ui_BarValue2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BarValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BarValue2, &ui_font_ArameBold30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarUnit2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarUnit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarUnit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarUnit2, 497);
    lv_obj_set_y(ui_BarUnit2, -115);
    lv_obj_set_align(ui_BarUnit2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BarUnit2, "V");
    lv_obj_set_style_text_color(ui_BarUnit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BarUnit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BarUnit2, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc2 = lv_arc_create(ui_MainScreen);
    lv_obj_set_width(ui_Arc2, 140);
    lv_obj_set_height(ui_Arc2, 140);
    lv_obj_set_x(ui_Arc2, -150);
    lv_obj_set_y(ui_Arc2, -20);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_Arc2, 0);
    lv_obj_set_style_arc_width(ui_Arc2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc2, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc2, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcValue2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcValue2, -149);
    lv_obj_set_y(ui_ArcValue2, -22);
    lv_obj_set_align(ui_ArcValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcValue2, "---");
    lv_obj_set_style_text_color(ui_ArcValue2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcValue2, &ui_font_ArameBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcUnit2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcUnit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcUnit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcUnit2, -150);
    lv_obj_set_y(ui_ArcUnit2, 0);
    lv_obj_set_align(ui_ArcUnit2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcUnit2, "---");
    lv_obj_set_style_text_color(ui_ArcUnit2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcUnit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcUnit2, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcName2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcName2, -149);
    lv_obj_set_y(ui_ArcName2, 29);
    lv_obj_set_align(ui_ArcName2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcName2, "---\n---");
    lv_obj_set_style_text_align(ui_ArcName2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcName2, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcBG2 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_ArcBG2, &ui_img_arcscalerr_png);
    lv_obj_set_width(ui_ArcBG2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcBG2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcBG2, -150);
    lv_obj_set_y(ui_ArcBG2, -26);
    lv_obj_set_align(ui_ArcBG2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcBG2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ArcBG2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ArcBG2, 200);

    ui_Arc1 = lv_arc_create(ui_MainScreen);
    lv_obj_set_width(ui_Arc1, 140);
    lv_obj_set_height(ui_Arc1, 140);
    lv_obj_set_x(ui_Arc1, -300);
    lv_obj_set_y(ui_Arc1, -19);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_Arc1, 0);
    lv_obj_set_style_arc_width(ui_Arc1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcValue1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcValue1, -301);
    lv_obj_set_y(ui_ArcValue1, -22);
    lv_obj_set_align(ui_ArcValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcValue1, "---");
    lv_obj_set_style_text_font(ui_ArcValue1, &ui_font_ArameBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcUnit1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcUnit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcUnit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcUnit1, -301);
    lv_obj_set_y(ui_ArcUnit1, 1);
    lv_obj_set_align(ui_ArcUnit1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcUnit1, "---");
    lv_obj_set_style_text_color(ui_ArcUnit1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcUnit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcUnit1, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcName1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcName1, -300);
    lv_obj_set_y(ui_ArcName1, 28);
    lv_obj_set_align(ui_ArcName1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcName1, "---\n---");
    lv_obj_set_style_text_align(ui_ArcName1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcName1, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcBG1 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_ArcBG1, &ui_img_arcscalerb_png);
    lv_obj_set_width(ui_ArcBG1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcBG1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcBG1, -300);
    lv_obj_set_y(ui_ArcBG1, -26);
    lv_obj_set_align(ui_ArcBG1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcBG1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ArcBG1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ArcBG1, 200);

    ui_Arc3 = lv_arc_create(ui_MainScreen);
    lv_obj_set_width(ui_Arc3, 140);
    lv_obj_set_height(ui_Arc3, 140);
    lv_obj_set_x(ui_Arc3, 150);
    lv_obj_set_y(ui_Arc3, -20);
    lv_obj_set_align(ui_Arc3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc3, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_Arc3, 0);
    lv_obj_set_style_arc_width(ui_Arc3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc3, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc3, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc3, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc3, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcValue3 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcValue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcValue3, 150);
    lv_obj_set_y(ui_ArcValue3, -22);
    lv_obj_set_align(ui_ArcValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcValue3, "---");
    lv_obj_set_style_text_color(ui_ArcValue3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcValue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcValue3, &ui_font_ArameBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcUnit3 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcUnit3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcUnit3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcUnit3, 150);
    lv_obj_set_y(ui_ArcUnit3, 1);
    lv_obj_set_align(ui_ArcUnit3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcUnit3, "°C");
    lv_obj_set_style_text_color(ui_ArcUnit3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcUnit3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcUnit3, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcName3 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcName3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcName3, 150);
    lv_obj_set_y(ui_ArcName3, 32);
    lv_obj_set_align(ui_ArcName3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcName3, "---\n---");
    lv_obj_set_style_text_align(ui_ArcName3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcName3, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcBG3 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_ArcBG3, &ui_img_arcscale_png);
    lv_obj_set_width(ui_ArcBG3, LV_SIZE_CONTENT);   /// -26
    lv_obj_set_height(ui_ArcBG3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcBG3, 150);
    lv_obj_set_y(ui_ArcBG3, -26);
    lv_obj_set_align(ui_ArcBG3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcBG3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ArcBG3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ArcBG3, 200);
    lv_obj_set_style_blend_mode(ui_ArcBG3, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc4 = lv_arc_create(ui_MainScreen);
    lv_obj_set_width(ui_Arc4, 140);
    lv_obj_set_height(ui_Arc4, 140);
    lv_obj_set_x(ui_Arc4, 300);
    lv_obj_set_y(ui_Arc4, -20);
    lv_obj_set_align(ui_Arc4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc4, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_Arc4, 0);
    lv_obj_set_style_arc_width(ui_Arc4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc4, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc4, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc4, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc4, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc4, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcValue4 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcValue4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcValue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcValue4, 300);
    lv_obj_set_y(ui_ArcValue4, -22);
    lv_obj_set_align(ui_ArcValue4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcValue4, "---");
    lv_obj_set_style_text_font(ui_ArcValue4, &ui_font_ArameBold40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcUnit4 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcUnit4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcUnit4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcUnit4, 300);
    lv_obj_set_y(ui_ArcUnit4, 1);
    lv_obj_set_align(ui_ArcUnit4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcUnit4, "---");
    lv_obj_set_style_text_color(ui_ArcUnit4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArcUnit4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcUnit4, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcName4 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ArcName4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcName4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcName4, 300);
    lv_obj_set_y(ui_ArcName4, 32);
    lv_obj_set_align(ui_ArcName4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArcName4, "---\n---");
    lv_obj_set_style_text_align(ui_ArcName4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArcName4, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcBG4 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_ArcBG4, &ui_img_arcscale_png);
    lv_obj_set_width(ui_ArcBG4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArcBG4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArcBG4, 300);
    lv_obj_set_y(ui_ArcBG4, -27);
    lv_obj_set_align(ui_ArcBG4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcBG4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ArcBG4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ArcBG4, 200);

    ui_Panel1 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel1, 70);
    lv_obj_set_height(ui_Panel1, 41);
    lv_obj_set_x(ui_Panel1, -300);
    lv_obj_set_y(ui_Panel1, 76);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelValue1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_PanelValue1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelValue1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PanelValue1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelValue1, "---");
    lv_obj_set_style_text_color(ui_PanelValue1, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PanelValue1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelValue1, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelName1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PanelName1, -300);
    lv_obj_set_y(ui_PanelName1, 96);
    lv_obj_set_align(ui_PanelName1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelName1, "---");
    lv_obj_set_style_text_font(ui_PanelName1, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelName1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelName1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelName1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelName1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelName1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel2, 70);
    lv_obj_set_height(ui_Panel2, 41);
    lv_obj_set_x(ui_Panel2, -225);
    lv_obj_set_y(ui_Panel2, 76);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelValue2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_PanelValue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelValue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PanelValue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelValue2, "---");
    lv_obj_set_style_text_color(ui_PanelValue2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PanelValue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelValue2, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelName2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PanelName2, -225);
    lv_obj_set_y(ui_PanelName2, 96);
    lv_obj_set_align(ui_PanelName2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelName2, "---");
    lv_obj_set_style_text_font(ui_PanelName2, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelName2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelName2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelName2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelName2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelName2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel3, 70);
    lv_obj_set_height(ui_Panel3, 41);
    lv_obj_set_x(ui_Panel3, -150);
    lv_obj_set_y(ui_Panel3, 76);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelValue3 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_PanelValue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PanelValue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelValue3, "---");
    lv_obj_set_style_text_color(ui_PanelValue3, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PanelValue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelValue3, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelName3 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelName3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PanelName3, -150);
    lv_obj_set_y(ui_PanelName3, 95);
    lv_obj_set_align(ui_PanelName3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelName3, "---");
    lv_obj_set_style_text_font(ui_PanelName3, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelName3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelName3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelName3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelName3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelName3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel4, 70);
    lv_obj_set_height(ui_Panel4, 41);
    lv_obj_set_x(ui_Panel4, 150);
    lv_obj_set_y(ui_Panel4, 76);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelValue4 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_PanelValue4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelValue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PanelValue4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelValue4, "---");
    lv_obj_set_style_text_color(ui_PanelValue4, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PanelValue4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelValue4, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelName4 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelName4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelName4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PanelName4, 150);
    lv_obj_set_y(ui_PanelName4, 95);
    lv_obj_set_align(ui_PanelName4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelName4, "---");
    lv_obj_set_style_text_font(ui_PanelName4, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelName4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelName4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelName4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelName4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelName4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel5, 70);
    lv_obj_set_height(ui_Panel5, 41);
    lv_obj_set_x(ui_Panel5, 225);
    lv_obj_set_y(ui_Panel5, 76);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelValue5 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_PanelValue5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelValue5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PanelValue5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelValue5, "---");
    lv_obj_set_style_text_color(ui_PanelValue5, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PanelValue5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelValue5, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelName5 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelName5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelName5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PanelName5, 225);
    lv_obj_set_y(ui_PanelName5, 95);
    lv_obj_set_align(ui_PanelName5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelName5, "---");
    lv_obj_set_style_text_font(ui_PanelName5, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelName5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelName5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelName5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelName5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelName5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_Panel6, 70);
    lv_obj_set_height(ui_Panel6, 41);
    lv_obj_set_x(ui_Panel6, 300);
    lv_obj_set_y(ui_Panel6, 76);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelValue6 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_PanelValue6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelValue6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PanelValue6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelValue6, "---");
    lv_obj_set_style_text_color(ui_PanelValue6, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PanelValue6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PanelValue6, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelName6 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_PanelName6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PanelName6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PanelName6, 300);
    lv_obj_set_y(ui_PanelName6, 95);
    lv_obj_set_align(ui_PanelName6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PanelName6, "---");
    lv_obj_set_style_text_font(ui_PanelName6, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelName6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelName6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelName6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelName6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelName6, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar3 = lv_bar_create(ui_MainScreen);
    lv_obj_set_width(ui_Bar3, 190);
    lv_obj_set_height(ui_Bar3, 23);
    lv_obj_set_x(ui_Bar3, -225);
    lv_obj_set_y(ui_Bar3, 127);
    lv_obj_set_align(ui_Bar3, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarBG3 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_BarBG3, &ui_img_barscalerb_png);
    lv_obj_set_width(ui_BarBG3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarBG3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarBG3, -225);
    lv_obj_set_y(ui_BarBG3, 137);
    lv_obj_set_align(ui_BarBG3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BarBG3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BarBG3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarName3 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarName3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarName3, -524);
    lv_obj_set_y(ui_BarName3, 153);
    lv_obj_set_align(ui_BarName3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BarName3, "---");
    lv_obj_set_style_text_font(ui_BarName3, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarValue3 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarValue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarValue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarValue3, -690);
    lv_obj_set_y(ui_BarValue3, 156);
    lv_obj_set_align(ui_BarValue3, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BarValue3, "000");
    lv_obj_set_style_text_color(ui_BarValue3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BarValue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BarValue3, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarUnit3 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarUnit3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarUnit3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarUnit3, 112);
    lv_obj_set_y(ui_BarUnit3, 154);
    lv_obj_set_align(ui_BarUnit3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BarUnit3, "---");
    lv_obj_set_style_text_color(ui_BarUnit3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BarUnit3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BarUnit3, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar4 = lv_bar_create(ui_MainScreen);
    lv_obj_set_width(ui_Bar4, 190);
    lv_obj_set_height(ui_Bar4, 23);
    lv_obj_set_x(ui_Bar4, 225);
    lv_obj_set_y(ui_Bar4, 127);
    lv_obj_set_align(ui_Bar4, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Bar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Bar4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BarBG4 = lv_img_create(ui_MainScreen);
    lv_img_set_src(ui_BarBG4, &ui_img_barscalered_png);
    lv_obj_set_width(ui_BarBG4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarBG4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarBG4, 225);
    lv_obj_set_y(ui_BarBG4, 137);
    lv_obj_set_align(ui_BarBG4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BarBG4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BarBG4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BarName4 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarName4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarName4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarName4, -74);
    lv_obj_set_y(ui_BarName4, 155);
    lv_obj_set_align(ui_BarName4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BarName4, "---");
    lv_obj_set_style_text_font(ui_BarName4, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarValue4 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarValue4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarValue4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarValue4, -239);
    lv_obj_set_y(ui_BarValue4, 158);
    lv_obj_set_align(ui_BarValue4, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_BarValue4, "---");
    lv_obj_set_style_text_color(ui_BarValue4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BarValue4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BarValue4, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarUnit4 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_BarUnit4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BarUnit4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BarUnit4, 562);
    lv_obj_set_y(ui_BarUnit4, 159);
    lv_obj_set_align(ui_BarUnit4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BarUnit4, "---");
    lv_obj_set_style_text_color(ui_BarUnit4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BarUnit4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BarUnit4, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button1, 113);
    lv_obj_set_height(ui_Button1, 51);
    lv_obj_set_x(ui_Button1, 331);
    lv_obj_set_y(ui_Button1, 203);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xAD0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonLabel1 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ButtonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ButtonLabel1, 333);
    lv_obj_set_y(ui_ButtonLabel1, 204);
    lv_obj_set_align(ui_ButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonLabel1, "START\nSTOP");
    lv_obj_set_style_text_align(ui_ButtonLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonLabel1, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CriticalAlertPanel = lv_obj_create(ui_MainScreen);
    lv_obj_set_width(ui_CriticalAlertPanel, 523);
    lv_obj_set_height(ui_CriticalAlertPanel, 247);
    lv_obj_set_x(ui_CriticalAlertPanel, 1);
    lv_obj_set_y(ui_CriticalAlertPanel, -9);
    lv_obj_set_align(ui_CriticalAlertPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CriticalAlertPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_CriticalAlertPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CriticalAlertPanel, lv_color_hex(0xD80000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CriticalAlertPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CriticalAlertText = lv_label_create(ui_CriticalAlertPanel);
    lv_obj_set_width(ui_CriticalAlertText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CriticalAlertText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CriticalAlertText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CriticalAlertText, "OIL PRESSURE\nLOW");
    lv_obj_set_style_text_color(ui_CriticalAlertText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CriticalAlertText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CriticalAlertText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CriticalAlertText, &ui_font_ArameBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button2, 79);
    lv_obj_set_height(ui_Button2, 40);
    lv_obj_set_x(ui_Button2, 229);
    lv_obj_set_y(ui_Button2, 209);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x092C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonLabel2 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ButtonLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ButtonLabel2, 230);
    lv_obj_set_y(ui_ButtonLabel2, 210);
    lv_obj_set_align(ui_ButtonLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonLabel2, "DATALOG\nOFF");
    lv_obj_set_style_text_align(ui_ButtonLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonLabel2, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClockLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ClockLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ClockLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ClockLabel, -236);
    lv_obj_set_y(ui_ClockLabel, 208);
    lv_obj_set_align(ui_ClockLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClockLabel, "--:-- -- | ---------- | --°C");
    lv_obj_set_style_text_font(ui_ClockLabel, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ClockLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ClockLabel, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClockLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ClockLabel, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ClockLabel, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ClockLabel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ClockLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_Button3, 79);
    lv_obj_set_height(ui_Button3, 40);
    lv_obj_set_x(ui_Button3, 143);
    lv_obj_set_y(ui_Button3, 209);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x00013C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonLabel3 = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_ButtonLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ButtonLabel3, 144);
    lv_obj_set_y(ui_ButtonLabel3, 210);
    lv_obj_set_align(ui_ButtonLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonLabel3, "LAUCH\nOFF");
    lv_obj_set_style_text_align(ui_ButtonLabel3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonLabel3, &ui_font_ArameBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);

}
