// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: ADVdash

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RpmsBG = lv_img_create(ui_Screen1);
lv_img_set_src(ui_RpmsBG, &ui_img_rpmscalet_png);
lv_obj_set_width( ui_RpmsBG, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RpmsBG, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RpmsBG, -87 );
lv_obj_set_y( ui_RpmsBG, -203 );
lv_obj_set_align( ui_RpmsBG, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_RpmsBG, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_RpmsBG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_RedLineBar = lv_bar_create(ui_Screen1);
lv_bar_set_value(ui_RedLineBar,100,LV_ANIM_OFF);
lv_obj_set_width( ui_RedLineBar, 311);
lv_obj_set_height( ui_RedLineBar, 30);
lv_obj_set_x( ui_RedLineBar, 61 );
lv_obj_set_y( ui_RedLineBar, -190 );
lv_obj_set_align( ui_RedLineBar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_RedLineBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RedLineBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RedLineBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_RedLineBar, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RedLineBar, lv_color_hex(0xFF0303), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RedLineBar, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_RedLineBar, LV_BLEND_MODE_MULTIPLY, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_RpmsBar = lv_bar_create(ui_Screen1);
lv_bar_set_value(ui_RpmsBar,25,LV_ANIM_OFF);
lv_obj_set_width( ui_RpmsBar, 597);
lv_obj_set_height( ui_RpmsBar, 30);
lv_obj_set_x( ui_RpmsBar, -89 );
lv_obj_set_y( ui_RpmsBar, -209 );
lv_obj_set_align( ui_RpmsBar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_RpmsBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RpmsBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RpmsBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_RpmsBar, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RpmsBar, lv_color_hex(0xDCDCDC), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RpmsBar, 250, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RpmsBar, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RpmsBar, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RpmsBar, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_RpmsBar, LV_BORDER_SIDE_NONE, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_RpmsValue = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_RpmsValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RpmsValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RpmsValue, 316 );
lv_obj_set_y( ui_RpmsValue, -203 );
lv_obj_set_align( ui_RpmsValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_RpmsValue,"2520");
lv_obj_set_style_text_font(ui_RpmsValue, &ui_font_ArameBold50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RpmsText = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_RpmsText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RpmsText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RpmsText, 352 );
lv_obj_set_y( ui_RpmsText, -173 );
lv_obj_set_align( ui_RpmsText, LV_ALIGN_CENTER );
lv_label_set_text(ui_RpmsText,"RPMS");
lv_obj_set_style_text_font(ui_RpmsText, &ui_font_ArameBold14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GearPanel = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_GearPanel, 140);
lv_obj_set_height( ui_GearPanel, 173);
lv_obj_set_x( ui_GearPanel, 7 );
lv_obj_set_y( ui_GearPanel, -17 );
lv_obj_set_align( ui_GearPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_GearPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_GearPanel, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_bg_color(ui_GearPanel, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GearPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_GearPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_GearPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GearValue = lv_label_create(ui_GearPanel);
lv_obj_set_width( ui_GearValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_GearValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_GearValue, 0 );
lv_obj_set_y( ui_GearValue, 5 );
lv_obj_set_align( ui_GearValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_GearValue,"N");
lv_obj_set_style_text_font(ui_GearValue, &ui_font_ArameBold150, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedPanel = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_SpeedPanel, 140);
lv_obj_set_height( ui_SpeedPanel, 42);
lv_obj_set_x( ui_SpeedPanel, 7 );
lv_obj_set_y( ui_SpeedPanel, -126 );
lv_obj_set_align( ui_SpeedPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SpeedPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_SpeedPanel, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_bg_color(ui_SpeedPanel, lv_color_hex(0xC4C4C4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SpeedPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SpeedPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SpeedPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedValue = lv_label_create(ui_SpeedPanel);
lv_obj_set_width( ui_SpeedValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpeedValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpeedValue, -27 );
lv_obj_set_y( ui_SpeedValue, 0 );
lv_obj_set_align( ui_SpeedValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpeedValue,"080");
lv_obj_set_style_text_color(ui_SpeedValue, lv_color_hex(0x020202), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SpeedValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SpeedValue, &ui_font_ArameBold30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeedUnit = lv_label_create(ui_SpeedPanel);
lv_obj_set_width( ui_SpeedUnit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpeedUnit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpeedUnit, 28 );
lv_obj_set_y( ui_SpeedUnit, -1 );
lv_obj_set_align( ui_SpeedUnit, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpeedUnit,"km/h");
lv_obj_set_style_text_color(ui_SpeedUnit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SpeedUnit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SpeedUnit, &ui_font_ArameBold14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TpsBar = lv_bar_create(ui_Screen1);
lv_bar_set_value(ui_TpsBar,25,LV_ANIM_OFF);
lv_obj_set_width( ui_TpsBar, 140);
lv_obj_set_height( ui_TpsBar, 10);
lv_obj_set_x( ui_TpsBar, 7 );
lv_obj_set_y( ui_TpsBar, 79 );
lv_obj_set_align( ui_TpsBar, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_TpsBar, lv_color_hex(0x1B1B1B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TpsBar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_TpsBar, lv_color_hex(0x06FF17), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TpsBar, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_DisplayB = lv_slider_create(ui_Screen1);
lv_slider_set_range(ui_DisplayB, 0,255);
lv_slider_set_value( ui_DisplayB, 255, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_DisplayB)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_DisplayB, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_DisplayB, 150);
lv_obj_set_height( ui_DisplayB, 17);
lv_obj_set_x( ui_DisplayB, 1 );
lv_obj_set_y( ui_DisplayB, 122 );
lv_obj_set_align( ui_DisplayB, LV_ALIGN_CENTER );



}
