// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: ADVdash

#include "../ui.h"

void ui_SettingsScreen_screen_init(void)
{
ui_SettingsScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SettingsScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingsScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Roller = lv_roller_create(ui_SettingsScreen);
lv_roller_set_options( ui_Roller, "RPMS\nBARS\nARCS\nPANELS\n", LV_ROLLER_MODE_NORMAL );
lv_obj_set_height( ui_Roller, 480);
lv_obj_set_width( ui_Roller, LV_SIZE_CONTENT);  /// 1
lv_obj_set_align( ui_Roller, LV_ALIGN_LEFT_MID );
lv_obj_set_style_text_font(ui_Roller, &ui_font_ArameBold14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Roller, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Roller, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Roller, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Roller, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller, lv_color_hex(0xE3D302), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller, 255, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_SetingsPanel = lv_obj_create(ui_SettingsScreen);
lv_obj_set_width( ui_SetingsPanel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetingsPanel, LV_SIZE_CONTENT);   /// -3
lv_obj_set_x( ui_SetingsPanel, 57 );
lv_obj_set_y( ui_SetingsPanel, 0 );
lv_obj_set_align( ui_SetingsPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SetingsPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_SetingsPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_SetingsPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SetingsPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SetingsPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SetingsPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SetingsPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SetingsPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SetingsPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SelectPanel = lv_obj_create(ui_SetingsPanel);
lv_obj_set_height( ui_SelectPanel, 53);
lv_obj_set_width( ui_SelectPanel, LV_SIZE_CONTENT);  /// 100
lv_obj_set_x( ui_SelectPanel, 10 );
lv_obj_set_y( ui_SelectPanel, 0 );
lv_obj_set_align( ui_SelectPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SelectPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SelectPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_SelectPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SelectPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SelectPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_GaugeNumberD = lv_dropdown_create(ui_SelectPanel);
lv_dropdown_set_options( ui_GaugeNumberD, "BAR 1\nBAR 2\nBAR 3" );
lv_obj_set_width( ui_GaugeNumberD, 135);
lv_obj_set_height( ui_GaugeNumberD, LV_SIZE_CONTENT);   /// 36
lv_obj_set_x( ui_GaugeNumberD, 1 );
lv_obj_set_y( ui_GaugeNumberD, 0 );
lv_obj_set_align( ui_GaugeNumberD, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_GaugeNumberD, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_GaugeNumberD, &ui_font_ArameBold14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_GaugeNumberD, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GaugeNumberD, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_GaugeNumberD, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_GaugeNumberD, &lv_font_montserrat_14, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_GaugeNumberD), &ui_font_ArameBold14,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_GaugeNumberD), lv_color_hex(0x222222),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_GaugeNumberD), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_GaugeNumberD), lv_color_hex(0x000000),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_GaugeNumberD), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_GaugeNumberD), lv_color_hex(0xE3D302),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_GaugeNumberD), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(lv_dropdown_get_list(ui_GaugeNumberD), lv_color_hex(0x000000),  LV_PART_SELECTED | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_GaugeNumberD), 255,  LV_PART_SELECTED| LV_STATE_CHECKED);
lv_obj_set_style_text_font(lv_dropdown_get_list(ui_GaugeNumberD), &ui_font_ArameBold14,  LV_PART_SELECTED| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_GaugeNumberD), lv_color_hex(0xE3D302),  LV_PART_SELECTED | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_GaugeNumberD), 255,  LV_PART_SELECTED| LV_STATE_CHECKED);

ui_GaugeTypeD = lv_dropdown_create(ui_SelectPanel);
lv_obj_set_width( ui_GaugeTypeD, 171);
lv_obj_set_height( ui_GaugeTypeD, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_GaugeTypeD, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_GaugeTypeD, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_GaugeTypeD, &ui_font_ArameBold14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_GaugeTypeD, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_GaugeTypeD, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_GaugeTypeD, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_GaugeTypeD, &lv_font_montserrat_14, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_GaugeTypeD), &ui_font_ArameBold14,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_GaugeTypeD), lv_color_hex(0x000000),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_GaugeTypeD), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_GaugeTypeD), lv_color_hex(0xE3D302),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_GaugeTypeD), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(lv_dropdown_get_list(ui_GaugeTypeD), lv_color_hex(0x000000),  LV_PART_SELECTED | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_GaugeTypeD), 255,  LV_PART_SELECTED| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_GaugeTypeD), lv_color_hex(0xE3D302),  LV_PART_SELECTED | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_GaugeTypeD), 255,  LV_PART_SELECTED| LV_STATE_CHECKED);

ui_UnitD = lv_dropdown_create(ui_SelectPanel);
lv_dropdown_set_options( ui_UnitD, "PSI" );
lv_obj_set_width( ui_UnitD, 69);
lv_obj_set_height( ui_UnitD, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_UnitD, -24 );
lv_obj_set_y( ui_UnitD, 0 );
lv_obj_set_align( ui_UnitD, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_UnitD, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_UnitD, &ui_font_ArameBold14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_UnitD, lv_color_hex(0x222222), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_UnitD, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_UnitD, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_UnitD, &lv_font_montserrat_14, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_UnitD), &ui_font_ArameBold14,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_dropdown_get_list(ui_UnitD), lv_color_hex(0x000000),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_UnitD), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_UnitD), lv_color_hex(0xE3D302),  LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_UnitD), 255,  LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(lv_dropdown_get_list(ui_UnitD), lv_color_hex(0x000000),  LV_PART_SELECTED | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_UnitD), 255,  LV_PART_SELECTED| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_UnitD), lv_color_hex(0xE3D302),  LV_PART_SELECTED | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_UnitD), 255,  LV_PART_SELECTED| LV_STATE_CHECKED);

ui_HighAlertPanel = lv_obj_create(ui_SetingsPanel);
lv_obj_set_width( ui_HighAlertPanel, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_HighAlertPanel, LV_SIZE_CONTENT);   /// 41
lv_obj_set_align( ui_HighAlertPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_HighAlertPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_HighAlertPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_HighAlertPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_HighAlertPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HighAlertPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HWAPanel = lv_obj_create(ui_HighAlertPanel);
lv_obj_set_width( ui_HWAPanel, 320);
lv_obj_set_height( ui_HWAPanel, 30);
lv_obj_set_align( ui_HWAPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_HWAPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_HWAPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_HWAPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_HWAPanel, lv_color_hex(0x262700), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HWAPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_HWAPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_HWAPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_HWAPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HWATittle = lv_label_create(ui_HWAPanel);
lv_obj_set_width( ui_HWATittle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HWATittle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HWATittle, -107 );
lv_obj_set_y( ui_HWATittle, 0 );
lv_obj_set_align( ui_HWATittle, LV_ALIGN_CENTER );
lv_label_set_text(ui_HWATittle,"HIGH Warning Level Alert =");
lv_obj_set_style_text_font(ui_HWATittle, &ui_font_ArameBold14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HWALabel = lv_label_create(ui_HWAPanel);
lv_obj_set_width( ui_HWALabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HWALabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HWALabel, 185 );
lv_obj_set_y( ui_HWALabel, 0 );
lv_obj_set_align( ui_HWALabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HWALabel,"0");
lv_obj_set_style_text_font(ui_HWALabel, &ui_font_ArameBold14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HWASlider = lv_slider_create(ui_HighAlertPanel);
lv_slider_set_range(ui_HWASlider, 1000,10000);
lv_slider_set_value( ui_HWASlider, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_HWASlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_HWASlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_HWASlider, 320);
lv_obj_set_height( ui_HWASlider, 10);
lv_obj_set_x( ui_HWASlider, -6 );
lv_obj_set_y( ui_HWASlider, 76 );
lv_obj_set_align( ui_HWASlider, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_HWASlider, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HWASlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_HWASlider, lv_color_hex(0xFFFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HWASlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_HWASlider, lv_color_hex(0xFFFF00), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HWASlider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_HDAPanel = lv_obj_create(ui_HighAlertPanel);
lv_obj_set_width( ui_HDAPanel, 320);
lv_obj_set_height( ui_HDAPanel, 30);
lv_obj_set_align( ui_HDAPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_HDAPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_HDAPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_HDAPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_HDAPanel, lv_color_hex(0x2F0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HDAPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_HDAPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HDATittle = lv_label_create(ui_HDAPanel);
lv_obj_set_width( ui_HDATittle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HDATittle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HDATittle, -105 );
lv_obj_set_y( ui_HDATittle, 55 );
lv_obj_set_align( ui_HDATittle, LV_ALIGN_CENTER );
lv_label_set_text(ui_HDATittle,"HIGH Danger Level Alert =");
lv_obj_set_style_text_font(ui_HDATittle, &ui_font_ArameBold14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HDALabel = lv_label_create(ui_HDAPanel);
lv_obj_set_width( ui_HDALabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HDALabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HDALabel, 189 );
lv_obj_set_y( ui_HDALabel, 57 );
lv_obj_set_align( ui_HDALabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HDALabel,"0");
lv_obj_set_style_text_font(ui_HDALabel, &ui_font_ArameBold14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HDASlider = lv_slider_create(ui_HighAlertPanel);
lv_slider_set_range(ui_HDASlider, 5000,10000);
lv_slider_set_value( ui_HDASlider, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_HDASlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_HDASlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_HDASlider, 320);
lv_obj_set_height( ui_HDASlider, 10);
lv_obj_set_x( ui_HDASlider, -7 );
lv_obj_set_y( ui_HDASlider, 22 );
lv_obj_set_align( ui_HDASlider, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_HDASlider, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HDASlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_HDASlider, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HDASlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_HDASlider, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HDASlider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LowAlertPanel = lv_obj_create(ui_SetingsPanel);
lv_obj_set_width( ui_LowAlertPanel, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_LowAlertPanel, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_LowAlertPanel, 2 );
lv_obj_set_y( ui_LowAlertPanel, 3 );
lv_obj_set_align( ui_LowAlertPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_LowAlertPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_LowAlertPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_LowAlertPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_LowAlertPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LowAlertPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LWAPanel = lv_obj_create(ui_LowAlertPanel);
lv_obj_set_width( ui_LWAPanel, 320);
lv_obj_set_height( ui_LWAPanel, 30);
lv_obj_set_align( ui_LWAPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_LWAPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_LWAPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_LWAPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_LWAPanel, lv_color_hex(0x262700), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LWAPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_LWAPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LWATittle = lv_label_create(ui_LWAPanel);
lv_obj_set_width( ui_LWATittle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LWATittle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LWATittle, -107 );
lv_obj_set_y( ui_LWATittle, 0 );
lv_obj_set_align( ui_LWATittle, LV_ALIGN_CENTER );
lv_label_set_text(ui_LWATittle,"LOW Warning Level Alert =");
lv_obj_set_style_text_font(ui_LWATittle, &ui_font_ArameBold14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LWALabel = lv_label_create(ui_LWAPanel);
lv_obj_set_width( ui_LWALabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LWALabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LWALabel, 185 );
lv_obj_set_y( ui_LWALabel, 0 );
lv_obj_set_align( ui_LWALabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LWALabel,"0");
lv_obj_set_style_text_font(ui_LWALabel, &ui_font_ArameBold14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LWASlider = lv_slider_create(ui_LowAlertPanel);
lv_slider_set_range(ui_LWASlider, 1000,10000);
lv_slider_set_value( ui_LWASlider, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_LWASlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_LWASlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_LWASlider, 320);
lv_obj_set_height( ui_LWASlider, 10);
lv_obj_set_x( ui_LWASlider, -6 );
lv_obj_set_y( ui_LWASlider, 76 );
lv_obj_set_align( ui_LWASlider, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_LWASlider, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LWASlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_LWASlider, lv_color_hex(0xFFFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LWASlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_LWASlider, lv_color_hex(0xFFFF00), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LWASlider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_LDAPanel = lv_obj_create(ui_LowAlertPanel);
lv_obj_set_width( ui_LDAPanel, 320);
lv_obj_set_height( ui_LDAPanel, 30);
lv_obj_set_align( ui_LDAPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_LDAPanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_LDAPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_LDAPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_LDAPanel, lv_color_hex(0x2F0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LDAPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_LDAPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LDATittle = lv_label_create(ui_LDAPanel);
lv_obj_set_width( ui_LDATittle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LDATittle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LDATittle, -105 );
lv_obj_set_y( ui_LDATittle, 55 );
lv_obj_set_align( ui_LDATittle, LV_ALIGN_CENTER );
lv_label_set_text(ui_LDATittle,"LOW Danger Level Alert =");
lv_obj_set_style_text_font(ui_LDATittle, &ui_font_ArameBold14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LDALabel = lv_label_create(ui_LDAPanel);
lv_obj_set_width( ui_LDALabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LDALabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LDALabel, 189 );
lv_obj_set_y( ui_LDALabel, 57 );
lv_obj_set_align( ui_LDALabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LDALabel,"0");
lv_obj_set_style_text_font(ui_LDALabel, &ui_font_ArameBold14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LDASlider = lv_slider_create(ui_LowAlertPanel);
lv_slider_set_range(ui_LDASlider, 5000,10000);
lv_slider_set_value( ui_LDASlider, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_LDASlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_LDASlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_LDASlider, 320);
lv_obj_set_height( ui_LDASlider, 10);
lv_obj_set_x( ui_LDASlider, -7 );
lv_obj_set_y( ui_LDASlider, 22 );
lv_obj_set_align( ui_LDASlider, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_LDASlider, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LDASlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_LDASlider, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LDASlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_LDASlider, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LDASlider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Panel7 = lv_obj_create(ui_SetingsPanel);
lv_obj_set_width( ui_Panel7, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Panel7, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel7,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SaveBTN = lv_btn_create(ui_Panel7);
lv_obj_set_height( ui_SaveBTN, 37);
lv_obj_set_width( ui_SaveBTN, LV_SIZE_CONTENT);  /// 127
lv_obj_set_align( ui_SaveBTN, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SaveBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SaveBTN, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SaveBTN, lv_color_hex(0xE3D302), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SaveBTN, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_SaveBTN, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SaveBTN, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SaveBTN, &ui_font_ArameBold14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_SaveBTN);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"sAVE sETTINGS");

ui_ResetBTN = lv_btn_create(ui_Panel7);
lv_obj_set_height( ui_ResetBTN, 37);
lv_obj_set_width( ui_ResetBTN, LV_SIZE_CONTENT);  /// 127
lv_obj_set_align( ui_ResetBTN, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ResetBTN, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ResetBTN, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ResetBTN, lv_color_hex(0xE3D302), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ResetBTN, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ResetBTN, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ResetBTN, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ResetBTN, &ui_font_ArameBold14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_ResetBTN);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Reset Now");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ExitBtn = lv_btn_create(ui_SettingsScreen);
lv_obj_set_width( ui_ExitBtn, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_ExitBtn, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_ExitBtn, 350 );
lv_obj_set_y( ui_ExitBtn, -200 );
lv_obj_set_align( ui_ExitBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ExitBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ExitBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ExitBtn, lv_color_hex(0xE3D302), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ExitBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ExitBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ExitBtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ExitBtn, &ui_font_ArameBold30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_ExitBtn);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"X");

lv_obj_add_event_cb(ui_HWASlider, ui_event_HWASlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_HDASlider, ui_event_HDASlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_LWASlider, ui_event_LWASlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_LDASlider, ui_event_LDASlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SaveBTN, ui_event_SaveBTN, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ResetBTN, ui_event_ResetBTN, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ExitBtn, ui_event_ExitBtn, LV_EVENT_ALL, NULL);

}
