// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: ADVdash

#include "../ui.h"

void ui_WelcomeScreen_screen_init(void)
{
    ui_WelcomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WelcomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WelcomeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WelcomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_carIMG = lv_img_create(ui_WelcomeScreen);
    lv_img_set_src(ui_carIMG, &ui_img_e30_png);
    lv_obj_set_width(ui_carIMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_carIMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_carIMG, 104);
    lv_obj_set_y(ui_carIMG, 34);
    lv_obj_set_align(ui_carIMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_carIMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_carIMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_carIMG, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_welcomeLabel = lv_label_create(ui_WelcomeScreen);
    lv_obj_set_width(ui_welcomeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_welcomeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_welcomeLabel, -32);
    lv_obj_set_y(ui_welcomeLabel, -56);
    lv_obj_set_align(ui_welcomeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_welcomeLabel, "BIENVENIDO DE NUEVO\nDANIEL....");
    lv_obj_set_style_text_font(ui_welcomeLabel, &ui_font_ArameBold50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_welcomeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bannerTextA = lv_textarea_create(ui_WelcomeScreen);
    lv_obj_set_width(ui_bannerTextA, 804);
    lv_obj_set_height(ui_bannerTextA, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_bannerTextA, 1);
    lv_obj_set_y(ui_bannerTextA, 260);
    lv_obj_set_align(ui_bannerTextA, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_bannerTextA, "---- | ---- | ----| ---- | ----");
    lv_textarea_set_one_line(ui_bannerTextA, true);
    lv_obj_set_style_text_color(ui_bannerTextA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_bannerTextA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_bannerTextA, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_bannerTextA, &ui_font_ArameBold20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_bannerTextA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bannerTextA, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bannerTextA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_bannerTextA, &ui_img_banner_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_bannerTextA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_proBannerIMG = lv_img_create(ui_WelcomeScreen);
    lv_img_set_src(ui_proBannerIMG, &ui_img_proup_png);
    lv_obj_set_width(ui_proBannerIMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_proBannerIMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_proBannerIMG, 0);
    lv_obj_set_y(ui_proBannerIMG, -265);
    lv_obj_set_align(ui_proBannerIMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_proBannerIMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_proBannerIMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_proIMG = lv_img_create(ui_WelcomeScreen);
    lv_img_set_src(ui_proIMG, &ui_img_proadvv1amarillo_png);
    lv_obj_set_width(ui_proIMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_proIMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_proIMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_proIMG, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_proIMG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
